// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EntityType.proto

package org.sq.gameDemo.common.proto;

public final class EntityTypeProto {
  private EntityTypeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code AttackType}
   */
  public enum AttackType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>AP = 0;</code>
     */
    AP(0),
    /**
     * <code>AD = 1;</code>
     */
    AD(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>AP = 0;</code>
     */
    public static final int AP_VALUE = 0;
    /**
     * <code>AD = 1;</code>
     */
    public static final int AD_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static AttackType valueOf(int value) {
      return forNumber(value);
    }

    public static AttackType forNumber(int value) {
      switch (value) {
        case 0: return AP;
        case 1: return AD;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AttackType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AttackType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AttackType>() {
            public AttackType findValueByNumber(int number) {
              return AttackType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return EntityTypeProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final AttackType[] VALUES = values();

    public static AttackType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AttackType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:AttackType)
  }

  public interface EntityTypeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EntityType)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     */
    String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 baseMP = 3;</code>
     */
    int getBaseMP();

    /**
     * <code>int32 baseHP = 4;</code>
     */
    int getBaseHP();

    /**
     * <code>.AttackType type = 5;</code>
     */
    int getTypeValue();
    /**
     * <code>.AttackType type = 5;</code>
     */
    AttackType getType();
  }
  /**
   * <pre>
   *实体类型
   * </pre>
   *
   * Protobuf type {@code EntityType}
   */
  public  static final class EntityType extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:EntityType)
      EntityTypeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EntityType.newBuilder() to construct.
    private EntityType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EntityType() {
      name_ = "";
      type_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new EntityType();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EntityType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              baseMP_ = input.readInt32();
              break;
            }
            case 32: {

              baseHP_ = input.readInt32();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EntityTypeProto.internal_static_EntityType_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EntityTypeProto.internal_static_EntityType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EntityType.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BASEMP_FIELD_NUMBER = 3;
    private int baseMP_;
    /**
     * <code>int32 baseMP = 3;</code>
     */
    public int getBaseMP() {
      return baseMP_;
    }

    public static final int BASEHP_FIELD_NUMBER = 4;
    private int baseHP_;
    /**
     * <code>int32 baseHP = 4;</code>
     */
    public int getBaseHP() {
      return baseHP_;
    }

    public static final int TYPE_FIELD_NUMBER = 5;
    private int type_;
    /**
     * <code>.AttackType type = 5;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.AttackType type = 5;</code>
     */
    public AttackType getType() {
      @SuppressWarnings("deprecation")
      AttackType result = AttackType.valueOf(type_);
      return result == null ? AttackType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (baseMP_ != 0) {
        output.writeInt32(3, baseMP_);
      }
      if (baseHP_ != 0) {
        output.writeInt32(4, baseHP_);
      }
      if (type_ != AttackType.AP.getNumber()) {
        output.writeEnum(5, type_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (baseMP_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, baseMP_);
      }
      if (baseHP_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, baseHP_);
      }
      if (type_ != AttackType.AP.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof EntityType)) {
        return super.equals(obj);
      }
      EntityType other = (EntityType) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getBaseMP()
          != other.getBaseMP()) return false;
      if (getBaseHP()
          != other.getBaseHP()) return false;
      if (type_ != other.type_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + BASEMP_FIELD_NUMBER;
      hash = (53 * hash) + getBaseMP();
      hash = (37 * hash) + BASEHP_FIELD_NUMBER;
      hash = (53 * hash) + getBaseHP();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static EntityType parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EntityType parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EntityType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EntityType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EntityType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EntityType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EntityType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EntityType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static EntityType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static EntityType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static EntityType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EntityType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EntityType prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *实体类型
     * </pre>
     *
     * Protobuf type {@code EntityType}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EntityType)
        EntityTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EntityTypeProto.internal_static_EntityType_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EntityTypeProto.internal_static_EntityType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EntityType.class, Builder.class);
      }

      // Construct using org.sq.gameDemo.common.proto.EntityTypeProto.EntityType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        baseMP_ = 0;

        baseHP_ = 0;

        type_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EntityTypeProto.internal_static_EntityType_descriptor;
      }

      @Override
      public EntityType getDefaultInstanceForType() {
        return EntityType.getDefaultInstance();
      }

      @Override
      public EntityType build() {
        EntityType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public EntityType buildPartial() {
        EntityType result = new EntityType(this);
        result.id_ = id_;
        result.name_ = name_;
        result.baseMP_ = baseMP_;
        result.baseHP_ = baseHP_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EntityType) {
          return mergeFrom((EntityType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EntityType other) {
        if (other == EntityType.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getBaseMP() != 0) {
          setBaseMP(other.getBaseMP());
        }
        if (other.getBaseHP() != 0) {
          setBaseHP(other.getBaseHP());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EntityType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EntityType) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int baseMP_ ;
      /**
       * <code>int32 baseMP = 3;</code>
       */
      public int getBaseMP() {
        return baseMP_;
      }
      /**
       * <code>int32 baseMP = 3;</code>
       */
      public Builder setBaseMP(int value) {
        
        baseMP_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 baseMP = 3;</code>
       */
      public Builder clearBaseMP() {
        
        baseMP_ = 0;
        onChanged();
        return this;
      }

      private int baseHP_ ;
      /**
       * <code>int32 baseHP = 4;</code>
       */
      public int getBaseHP() {
        return baseHP_;
      }
      /**
       * <code>int32 baseHP = 4;</code>
       */
      public Builder setBaseHP(int value) {
        
        baseHP_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 baseHP = 4;</code>
       */
      public Builder clearBaseHP() {
        
        baseHP_ = 0;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.AttackType type = 5;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.AttackType type = 5;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.AttackType type = 5;</code>
       */
      public AttackType getType() {
        @SuppressWarnings("deprecation")
        AttackType result = AttackType.valueOf(type_);
        return result == null ? AttackType.UNRECOGNIZED : result;
      }
      /**
       * <code>.AttackType type = 5;</code>
       */
      public Builder setType(AttackType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.AttackType type = 5;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:EntityType)
    }

    // @@protoc_insertion_point(class_scope:EntityType)
    private static final EntityType DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EntityType();
    }

    public static EntityType getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EntityType>
        PARSER = new com.google.protobuf.AbstractParser<EntityType>() {
      @Override
      public EntityType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EntityType(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EntityType> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<EntityType> getParserForType() {
      return PARSER;
    }

    @Override
    public EntityType getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EntityTypeRequestInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EntityTypeRequestInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>uint64 msg_id = 1;</code>
     */
    long getMsgId();

    /**
     * <pre>
     *时间戳(单位:毫秒)
     * </pre>
     *
     * <code>uint64 time = 2;</code>
     */
    long getTime();

    /**
     * <pre>
     *获取全部写-1
     * </pre>
     *
     * <code>int32 typeId = 3;</code>
     */
    int getTypeId();
  }
  /**
   * <pre>
   *请求
   * </pre>
   *
   * Protobuf type {@code EntityTypeRequestInfo}
   */
  public  static final class EntityTypeRequestInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:EntityTypeRequestInfo)
      EntityTypeRequestInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EntityTypeRequestInfo.newBuilder() to construct.
    private EntityTypeRequestInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EntityTypeRequestInfo() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new EntityTypeRequestInfo();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EntityTypeRequestInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              msgId_ = input.readUInt64();
              break;
            }
            case 16: {

              time_ = input.readUInt64();
              break;
            }
            case 24: {

              typeId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EntityTypeProto.internal_static_EntityTypeRequestInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EntityTypeProto.internal_static_EntityTypeRequestInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EntityTypeRequestInfo.class, Builder.class);
    }

    public static final int MSG_ID_FIELD_NUMBER = 1;
    private long msgId_;
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>uint64 msg_id = 1;</code>
     */
    public long getMsgId() {
      return msgId_;
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private long time_;
    /**
     * <pre>
     *时间戳(单位:毫秒)
     * </pre>
     *
     * <code>uint64 time = 2;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int TYPEID_FIELD_NUMBER = 3;
    private int typeId_;
    /**
     * <pre>
     *获取全部写-1
     * </pre>
     *
     * <code>int32 typeId = 3;</code>
     */
    public int getTypeId() {
      return typeId_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgId_ != 0L) {
        output.writeUInt64(1, msgId_);
      }
      if (time_ != 0L) {
        output.writeUInt64(2, time_);
      }
      if (typeId_ != 0) {
        output.writeInt32(3, typeId_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, msgId_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, time_);
      }
      if (typeId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, typeId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof EntityTypeRequestInfo)) {
        return super.equals(obj);
      }
      EntityTypeRequestInfo other = (EntityTypeRequestInfo) obj;

      if (getMsgId()
          != other.getMsgId()) return false;
      if (getTime()
          != other.getTime()) return false;
      if (getTypeId()
          != other.getTypeId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSG_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgId());
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (37 * hash) + TYPEID_FIELD_NUMBER;
      hash = (53 * hash) + getTypeId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static EntityTypeRequestInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EntityTypeRequestInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EntityTypeRequestInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EntityTypeRequestInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EntityTypeRequestInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EntityTypeRequestInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EntityTypeRequestInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EntityTypeRequestInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static EntityTypeRequestInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static EntityTypeRequestInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static EntityTypeRequestInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EntityTypeRequestInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EntityTypeRequestInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *请求
     * </pre>
     *
     * Protobuf type {@code EntityTypeRequestInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EntityTypeRequestInfo)
        EntityTypeRequestInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EntityTypeProto.internal_static_EntityTypeRequestInfo_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EntityTypeProto.internal_static_EntityTypeRequestInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EntityTypeRequestInfo.class, Builder.class);
      }

      // Construct using org.sq.gameDemo.common.proto.EntityTypeProto.EntityTypeRequestInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        msgId_ = 0L;

        time_ = 0L;

        typeId_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EntityTypeProto.internal_static_EntityTypeRequestInfo_descriptor;
      }

      @Override
      public EntityTypeRequestInfo getDefaultInstanceForType() {
        return EntityTypeRequestInfo.getDefaultInstance();
      }

      @Override
      public EntityTypeRequestInfo build() {
        EntityTypeRequestInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public EntityTypeRequestInfo buildPartial() {
        EntityTypeRequestInfo result = new EntityTypeRequestInfo(this);
        result.msgId_ = msgId_;
        result.time_ = time_;
        result.typeId_ = typeId_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EntityTypeRequestInfo) {
          return mergeFrom((EntityTypeRequestInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EntityTypeRequestInfo other) {
        if (other == EntityTypeRequestInfo.getDefaultInstance()) return this;
        if (other.getMsgId() != 0L) {
          setMsgId(other.getMsgId());
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (other.getTypeId() != 0) {
          setTypeId(other.getTypeId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EntityTypeRequestInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EntityTypeRequestInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long msgId_ ;
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>uint64 msg_id = 1;</code>
       */
      public long getMsgId() {
        return msgId_;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>uint64 msg_id = 1;</code>
       */
      public Builder setMsgId(long value) {
        
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>uint64 msg_id = 1;</code>
       */
      public Builder clearMsgId() {
        
        msgId_ = 0L;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <pre>
       *时间戳(单位:毫秒)
       * </pre>
       *
       * <code>uint64 time = 2;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <pre>
       *时间戳(单位:毫秒)
       * </pre>
       *
       * <code>uint64 time = 2;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间戳(单位:毫秒)
       * </pre>
       *
       * <code>uint64 time = 2;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private int typeId_ ;
      /**
       * <pre>
       *获取全部写-1
       * </pre>
       *
       * <code>int32 typeId = 3;</code>
       */
      public int getTypeId() {
        return typeId_;
      }
      /**
       * <pre>
       *获取全部写-1
       * </pre>
       *
       * <code>int32 typeId = 3;</code>
       */
      public Builder setTypeId(int value) {
        
        typeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *获取全部写-1
       * </pre>
       *
       * <code>int32 typeId = 3;</code>
       */
      public Builder clearTypeId() {
        
        typeId_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:EntityTypeRequestInfo)
    }

    // @@protoc_insertion_point(class_scope:EntityTypeRequestInfo)
    private static final EntityTypeRequestInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EntityTypeRequestInfo();
    }

    public static EntityTypeRequestInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EntityTypeRequestInfo>
        PARSER = new com.google.protobuf.AbstractParser<EntityTypeRequestInfo>() {
      @Override
      public EntityTypeRequestInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EntityTypeRequestInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EntityTypeRequestInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<EntityTypeRequestInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public EntityTypeRequestInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EntityTypeResponseInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EntityTypeResponseInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>uint64 msg_id = 1;</code>
     */
    long getMsgId();

    /**
     * <code>int32 result = 2;</code>
     */
    int getResult();

    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>uint64 time = 3;</code>
     */
    long getTime();

    /**
     * <code>string content = 4;</code>
     */
    String getContent();
    /**
     * <code>string content = 4;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>repeated .EntityType entityType = 5;</code>
     */
    java.util.List<EntityType>
        getEntityTypeList();
    /**
     * <code>repeated .EntityType entityType = 5;</code>
     */
    EntityType getEntityType(int index);
    /**
     * <code>repeated .EntityType entityType = 5;</code>
     */
    int getEntityTypeCount();
    /**
     * <code>repeated .EntityType entityType = 5;</code>
     */
    java.util.List<? extends EntityTypeOrBuilder>
        getEntityTypeOrBuilderList();
    /**
     * <code>repeated .EntityType entityType = 5;</code>
     */
    EntityTypeOrBuilder getEntityTypeOrBuilder(
            int index);
  }
  /**
   * <pre>
   *响应
   * </pre>
   *
   * Protobuf type {@code EntityTypeResponseInfo}
   */
  public  static final class EntityTypeResponseInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:EntityTypeResponseInfo)
      EntityTypeResponseInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EntityTypeResponseInfo.newBuilder() to construct.
    private EntityTypeResponseInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EntityTypeResponseInfo() {
      content_ = "";
      entityType_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new EntityTypeResponseInfo();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EntityTypeResponseInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              msgId_ = input.readUInt64();
              break;
            }
            case 16: {

              result_ = input.readInt32();
              break;
            }
            case 24: {

              time_ = input.readUInt64();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                entityType_ = new java.util.ArrayList<EntityType>();
                mutable_bitField0_ |= 0x00000001;
              }
              entityType_.add(
                  input.readMessage(EntityType.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          entityType_ = java.util.Collections.unmodifiableList(entityType_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EntityTypeProto.internal_static_EntityTypeResponseInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EntityTypeProto.internal_static_EntityTypeResponseInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EntityTypeResponseInfo.class, Builder.class);
    }

    public static final int MSG_ID_FIELD_NUMBER = 1;
    private long msgId_;
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>uint64 msg_id = 1;</code>
     */
    public long getMsgId() {
      return msgId_;
    }

    public static final int RESULT_FIELD_NUMBER = 2;
    private int result_;
    /**
     * <code>int32 result = 2;</code>
     */
    public int getResult() {
      return result_;
    }

    public static final int TIME_FIELD_NUMBER = 3;
    private long time_;
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>uint64 time = 3;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    private volatile Object content_;
    /**
     * <code>string content = 4;</code>
     */
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 4;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENTITYTYPE_FIELD_NUMBER = 5;
    private java.util.List<EntityType> entityType_;
    /**
     * <code>repeated .EntityType entityType = 5;</code>
     */
    public java.util.List<EntityType> getEntityTypeList() {
      return entityType_;
    }
    /**
     * <code>repeated .EntityType entityType = 5;</code>
     */
    public java.util.List<? extends EntityTypeOrBuilder>
        getEntityTypeOrBuilderList() {
      return entityType_;
    }
    /**
     * <code>repeated .EntityType entityType = 5;</code>
     */
    public int getEntityTypeCount() {
      return entityType_.size();
    }
    /**
     * <code>repeated .EntityType entityType = 5;</code>
     */
    public EntityType getEntityType(int index) {
      return entityType_.get(index);
    }
    /**
     * <code>repeated .EntityType entityType = 5;</code>
     */
    public EntityTypeOrBuilder getEntityTypeOrBuilder(
        int index) {
      return entityType_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgId_ != 0L) {
        output.writeUInt64(1, msgId_);
      }
      if (result_ != 0) {
        output.writeInt32(2, result_);
      }
      if (time_ != 0L) {
        output.writeUInt64(3, time_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, content_);
      }
      for (int i = 0; i < entityType_.size(); i++) {
        output.writeMessage(5, entityType_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, msgId_);
      }
      if (result_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, result_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, time_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, content_);
      }
      for (int i = 0; i < entityType_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, entityType_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof EntityTypeResponseInfo)) {
        return super.equals(obj);
      }
      EntityTypeResponseInfo other = (EntityTypeResponseInfo) obj;

      if (getMsgId()
          != other.getMsgId()) return false;
      if (getResult()
          != other.getResult()) return false;
      if (getTime()
          != other.getTime()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!getEntityTypeList()
          .equals(other.getEntityTypeList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSG_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgId());
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      if (getEntityTypeCount() > 0) {
        hash = (37 * hash) + ENTITYTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getEntityTypeList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static EntityTypeResponseInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EntityTypeResponseInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EntityTypeResponseInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EntityTypeResponseInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EntityTypeResponseInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EntityTypeResponseInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EntityTypeResponseInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EntityTypeResponseInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static EntityTypeResponseInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static EntityTypeResponseInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static EntityTypeResponseInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EntityTypeResponseInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EntityTypeResponseInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *响应
     * </pre>
     *
     * Protobuf type {@code EntityTypeResponseInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EntityTypeResponseInfo)
        EntityTypeResponseInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EntityTypeProto.internal_static_EntityTypeResponseInfo_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EntityTypeProto.internal_static_EntityTypeResponseInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EntityTypeResponseInfo.class, Builder.class);
      }

      // Construct using org.sq.gameDemo.common.proto.EntityTypeProto.EntityTypeResponseInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEntityTypeFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        msgId_ = 0L;

        result_ = 0;

        time_ = 0L;

        content_ = "";

        if (entityTypeBuilder_ == null) {
          entityType_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          entityTypeBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EntityTypeProto.internal_static_EntityTypeResponseInfo_descriptor;
      }

      @Override
      public EntityTypeResponseInfo getDefaultInstanceForType() {
        return EntityTypeResponseInfo.getDefaultInstance();
      }

      @Override
      public EntityTypeResponseInfo build() {
        EntityTypeResponseInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public EntityTypeResponseInfo buildPartial() {
        EntityTypeResponseInfo result = new EntityTypeResponseInfo(this);
        int from_bitField0_ = bitField0_;
        result.msgId_ = msgId_;
        result.result_ = result_;
        result.time_ = time_;
        result.content_ = content_;
        if (entityTypeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            entityType_ = java.util.Collections.unmodifiableList(entityType_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.entityType_ = entityType_;
        } else {
          result.entityType_ = entityTypeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EntityTypeResponseInfo) {
          return mergeFrom((EntityTypeResponseInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EntityTypeResponseInfo other) {
        if (other == EntityTypeResponseInfo.getDefaultInstance()) return this;
        if (other.getMsgId() != 0L) {
          setMsgId(other.getMsgId());
        }
        if (other.getResult() != 0) {
          setResult(other.getResult());
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (entityTypeBuilder_ == null) {
          if (!other.entityType_.isEmpty()) {
            if (entityType_.isEmpty()) {
              entityType_ = other.entityType_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEntityTypeIsMutable();
              entityType_.addAll(other.entityType_);
            }
            onChanged();
          }
        } else {
          if (!other.entityType_.isEmpty()) {
            if (entityTypeBuilder_.isEmpty()) {
              entityTypeBuilder_.dispose();
              entityTypeBuilder_ = null;
              entityType_ = other.entityType_;
              bitField0_ = (bitField0_ & ~0x00000001);
              entityTypeBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEntityTypeFieldBuilder() : null;
            } else {
              entityTypeBuilder_.addAllMessages(other.entityType_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EntityTypeResponseInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EntityTypeResponseInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long msgId_ ;
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>uint64 msg_id = 1;</code>
       */
      public long getMsgId() {
        return msgId_;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>uint64 msg_id = 1;</code>
       */
      public Builder setMsgId(long value) {
        
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>uint64 msg_id = 1;</code>
       */
      public Builder clearMsgId() {
        
        msgId_ = 0L;
        onChanged();
        return this;
      }

      private int result_ ;
      /**
       * <code>int32 result = 2;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>int32 result = 2;</code>
       */
      public Builder setResult(int value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 result = 2;</code>
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>uint64 time = 3;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>uint64 time = 3;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>uint64 time = 3;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <code>string content = 4;</code>
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string content = 4;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 4;</code>
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 4;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 4;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private java.util.List<EntityType> entityType_ =
        java.util.Collections.emptyList();
      private void ensureEntityTypeIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          entityType_ = new java.util.ArrayList<EntityType>(entityType_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          EntityType, EntityType.Builder, EntityTypeOrBuilder> entityTypeBuilder_;

      /**
       * <code>repeated .EntityType entityType = 5;</code>
       */
      public java.util.List<EntityType> getEntityTypeList() {
        if (entityTypeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(entityType_);
        } else {
          return entityTypeBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .EntityType entityType = 5;</code>
       */
      public int getEntityTypeCount() {
        if (entityTypeBuilder_ == null) {
          return entityType_.size();
        } else {
          return entityTypeBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .EntityType entityType = 5;</code>
       */
      public EntityType getEntityType(int index) {
        if (entityTypeBuilder_ == null) {
          return entityType_.get(index);
        } else {
          return entityTypeBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .EntityType entityType = 5;</code>
       */
      public Builder setEntityType(
          int index, EntityType value) {
        if (entityTypeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntityTypeIsMutable();
          entityType_.set(index, value);
          onChanged();
        } else {
          entityTypeBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .EntityType entityType = 5;</code>
       */
      public Builder setEntityType(
          int index, EntityType.Builder builderForValue) {
        if (entityTypeBuilder_ == null) {
          ensureEntityTypeIsMutable();
          entityType_.set(index, builderForValue.build());
          onChanged();
        } else {
          entityTypeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .EntityType entityType = 5;</code>
       */
      public Builder addEntityType(EntityType value) {
        if (entityTypeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntityTypeIsMutable();
          entityType_.add(value);
          onChanged();
        } else {
          entityTypeBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .EntityType entityType = 5;</code>
       */
      public Builder addEntityType(
          int index, EntityType value) {
        if (entityTypeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntityTypeIsMutable();
          entityType_.add(index, value);
          onChanged();
        } else {
          entityTypeBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .EntityType entityType = 5;</code>
       */
      public Builder addEntityType(
          EntityType.Builder builderForValue) {
        if (entityTypeBuilder_ == null) {
          ensureEntityTypeIsMutable();
          entityType_.add(builderForValue.build());
          onChanged();
        } else {
          entityTypeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .EntityType entityType = 5;</code>
       */
      public Builder addEntityType(
          int index, EntityType.Builder builderForValue) {
        if (entityTypeBuilder_ == null) {
          ensureEntityTypeIsMutable();
          entityType_.add(index, builderForValue.build());
          onChanged();
        } else {
          entityTypeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .EntityType entityType = 5;</code>
       */
      public Builder addAllEntityType(
          Iterable<? extends EntityType> values) {
        if (entityTypeBuilder_ == null) {
          ensureEntityTypeIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, entityType_);
          onChanged();
        } else {
          entityTypeBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .EntityType entityType = 5;</code>
       */
      public Builder clearEntityType() {
        if (entityTypeBuilder_ == null) {
          entityType_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          entityTypeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .EntityType entityType = 5;</code>
       */
      public Builder removeEntityType(int index) {
        if (entityTypeBuilder_ == null) {
          ensureEntityTypeIsMutable();
          entityType_.remove(index);
          onChanged();
        } else {
          entityTypeBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .EntityType entityType = 5;</code>
       */
      public EntityType.Builder getEntityTypeBuilder(
          int index) {
        return getEntityTypeFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .EntityType entityType = 5;</code>
       */
      public EntityTypeOrBuilder getEntityTypeOrBuilder(
          int index) {
        if (entityTypeBuilder_ == null) {
          return entityType_.get(index);  } else {
          return entityTypeBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .EntityType entityType = 5;</code>
       */
      public java.util.List<? extends EntityTypeOrBuilder>
           getEntityTypeOrBuilderList() {
        if (entityTypeBuilder_ != null) {
          return entityTypeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(entityType_);
        }
      }
      /**
       * <code>repeated .EntityType entityType = 5;</code>
       */
      public EntityType.Builder addEntityTypeBuilder() {
        return getEntityTypeFieldBuilder().addBuilder(
            EntityType.getDefaultInstance());
      }
      /**
       * <code>repeated .EntityType entityType = 5;</code>
       */
      public EntityType.Builder addEntityTypeBuilder(
          int index) {
        return getEntityTypeFieldBuilder().addBuilder(
            index, EntityType.getDefaultInstance());
      }
      /**
       * <code>repeated .EntityType entityType = 5;</code>
       */
      public java.util.List<EntityType.Builder>
           getEntityTypeBuilderList() {
        return getEntityTypeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          EntityType, EntityType.Builder, EntityTypeOrBuilder>
          getEntityTypeFieldBuilder() {
        if (entityTypeBuilder_ == null) {
          entityTypeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              EntityType, EntityType.Builder, EntityTypeOrBuilder>(
                  entityType_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          entityType_ = null;
        }
        return entityTypeBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:EntityTypeResponseInfo)
    }

    // @@protoc_insertion_point(class_scope:EntityTypeResponseInfo)
    private static final EntityTypeResponseInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EntityTypeResponseInfo();
    }

    public static EntityTypeResponseInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EntityTypeResponseInfo>
        PARSER = new com.google.protobuf.AbstractParser<EntityTypeResponseInfo>() {
      @Override
      public EntityTypeResponseInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EntityTypeResponseInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EntityTypeResponseInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<EntityTypeResponseInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public EntityTypeResponseInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EntityType_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EntityType_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EntityTypeRequestInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EntityTypeRequestInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EntityTypeResponseInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EntityTypeResponseInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020EntityType.proto\"a\n\nEntityType\022\n\n\002id\030\001" +
      " \001(\005\022\014\n\004name\030\002 \001(\t\022\016\n\006baseMP\030\003 \001(\005\022\016\n\006ba" +
      "seHP\030\004 \001(\005\022\031\n\004type\030\005 \001(\0162\013.AttackType\"E\n" +
      "\025EntityTypeRequestInfo\022\016\n\006msg_id\030\001 \001(\004\022\014" +
      "\n\004time\030\002 \001(\004\022\016\n\006typeId\030\003 \001(\005\"x\n\026EntityTy" +
      "peResponseInfo\022\016\n\006msg_id\030\001 \001(\004\022\016\n\006result" +
      "\030\002 \001(\005\022\014\n\004time\030\003 \001(\004\022\017\n\007content\030\004 \001(\t\022\037\n" +
      "\nentityType\030\005 \003(\0132\013.EntityType*\034\n\nAttack" +
      "Type\022\006\n\002AP\020\000\022\006\n\002AD\020\001B/\n\034org.sq.gameDemo." +
      "common.protoB\017EntityTypeProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_EntityType_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EntityType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EntityType_descriptor,
        new String[] { "Id", "Name", "BaseMP", "BaseHP", "Type", });
    internal_static_EntityTypeRequestInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EntityTypeRequestInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EntityTypeRequestInfo_descriptor,
        new String[] { "MsgId", "Time", "TypeId", });
    internal_static_EntityTypeResponseInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_EntityTypeResponseInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EntityTypeResponseInfo_descriptor,
        new String[] { "MsgId", "Result", "Time", "Content", "EntityType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
