// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SenceEntity.proto

package org.sq.gameDemo.common.proto;

public final class SenceEntityProto {
  private SenceEntityProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SenceEntityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SenceEntity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>int32 senceId = 2;</code>
     */
    int getSenceId();

    /**
     * <pre>
     *之后版本需要就去掉。。。
     * </pre>
     *
     * <code>int32 num = 3;</code>
     */
    int getNum();

    /**
     * <code>int32 state = 4;</code>
     */
    int getState();

    /**
     * <code>repeated .EntityType type = 5;</code>
     */
    java.util.List<EntityTypeProto.EntityType>
        getTypeList();
    /**
     * <code>repeated .EntityType type = 5;</code>
     */
    EntityTypeProto.EntityType getType(int index);
    /**
     * <code>repeated .EntityType type = 5;</code>
     */
    int getTypeCount();
    /**
     * <code>repeated .EntityType type = 5;</code>
     */
    java.util.List<? extends EntityTypeProto.EntityTypeOrBuilder>
        getTypeOrBuilderList();
    /**
     * <code>repeated .EntityType type = 5;</code>
     */
    EntityTypeProto.EntityTypeOrBuilder getTypeOrBuilder(
            int index);
  }
  /**
   * <pre>
   *场景实体 npc 野怪
   * </pre>
   *
   * Protobuf type {@code SenceEntity}
   */
  public  static final class SenceEntity extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SenceEntity)
      SenceEntityOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SenceEntity.newBuilder() to construct.
    private SenceEntity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SenceEntity() {
      type_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new SenceEntity();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SenceEntity(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 16: {

              senceId_ = input.readInt32();
              break;
            }
            case 24: {

              num_ = input.readInt32();
              break;
            }
            case 32: {

              state_ = input.readInt32();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                type_ = new java.util.ArrayList<EntityTypeProto.EntityType>();
                mutable_bitField0_ |= 0x00000001;
              }
              type_.add(
                  input.readMessage(EntityTypeProto.EntityType.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          type_ = java.util.Collections.unmodifiableList(type_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SenceEntityProto.internal_static_SenceEntity_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SenceEntityProto.internal_static_SenceEntity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SenceEntity.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int SENCEID_FIELD_NUMBER = 2;
    private int senceId_;
    /**
     * <code>int32 senceId = 2;</code>
     */
    public int getSenceId() {
      return senceId_;
    }

    public static final int NUM_FIELD_NUMBER = 3;
    private int num_;
    /**
     * <pre>
     *之后版本需要就去掉。。。
     * </pre>
     *
     * <code>int32 num = 3;</code>
     */
    public int getNum() {
      return num_;
    }

    public static final int STATE_FIELD_NUMBER = 4;
    private int state_;
    /**
     * <code>int32 state = 4;</code>
     */
    public int getState() {
      return state_;
    }

    public static final int TYPE_FIELD_NUMBER = 5;
    private java.util.List<EntityTypeProto.EntityType> type_;
    /**
     * <code>repeated .EntityType type = 5;</code>
     */
    public java.util.List<EntityTypeProto.EntityType> getTypeList() {
      return type_;
    }
    /**
     * <code>repeated .EntityType type = 5;</code>
     */
    public java.util.List<? extends EntityTypeProto.EntityTypeOrBuilder>
        getTypeOrBuilderList() {
      return type_;
    }
    /**
     * <code>repeated .EntityType type = 5;</code>
     */
    public int getTypeCount() {
      return type_.size();
    }
    /**
     * <code>repeated .EntityType type = 5;</code>
     */
    public EntityTypeProto.EntityType getType(int index) {
      return type_.get(index);
    }
    /**
     * <code>repeated .EntityType type = 5;</code>
     */
    public EntityTypeProto.EntityTypeOrBuilder getTypeOrBuilder(
        int index) {
      return type_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (senceId_ != 0) {
        output.writeInt32(2, senceId_);
      }
      if (num_ != 0) {
        output.writeInt32(3, num_);
      }
      if (state_ != 0) {
        output.writeInt32(4, state_);
      }
      for (int i = 0; i < type_.size(); i++) {
        output.writeMessage(5, type_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (senceId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, senceId_);
      }
      if (num_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, num_);
      }
      if (state_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, state_);
      }
      for (int i = 0; i < type_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, type_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SenceEntity)) {
        return super.equals(obj);
      }
      SenceEntity other = (SenceEntity) obj;

      if (getId()
          != other.getId()) return false;
      if (getSenceId()
          != other.getSenceId()) return false;
      if (getNum()
          != other.getNum()) return false;
      if (getState()
          != other.getState()) return false;
      if (!getTypeList()
          .equals(other.getTypeList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + SENCEID_FIELD_NUMBER;
      hash = (53 * hash) + getSenceId();
      hash = (37 * hash) + NUM_FIELD_NUMBER;
      hash = (53 * hash) + getNum();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + getState();
      if (getTypeCount() > 0) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getTypeList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SenceEntity parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SenceEntity parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SenceEntity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SenceEntity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SenceEntity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SenceEntity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SenceEntity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SenceEntity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SenceEntity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SenceEntity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SenceEntity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SenceEntity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SenceEntity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *场景实体 npc 野怪
     * </pre>
     *
     * Protobuf type {@code SenceEntity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SenceEntity)
        SenceEntityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SenceEntityProto.internal_static_SenceEntity_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SenceEntityProto.internal_static_SenceEntity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SenceEntity.class, Builder.class);
      }

      // Construct using org.sq.gameDemo.common.proto.SenceEntityProto.SenceEntity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTypeFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        senceId_ = 0;

        num_ = 0;

        state_ = 0;

        if (typeBuilder_ == null) {
          type_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          typeBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SenceEntityProto.internal_static_SenceEntity_descriptor;
      }

      @Override
      public SenceEntity getDefaultInstanceForType() {
        return SenceEntity.getDefaultInstance();
      }

      @Override
      public SenceEntity build() {
        SenceEntity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public SenceEntity buildPartial() {
        SenceEntity result = new SenceEntity(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.senceId_ = senceId_;
        result.num_ = num_;
        result.state_ = state_;
        if (typeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            type_ = java.util.Collections.unmodifiableList(type_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.type_ = type_;
        } else {
          result.type_ = typeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SenceEntity) {
          return mergeFrom((SenceEntity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SenceEntity other) {
        if (other == SenceEntity.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getSenceId() != 0) {
          setSenceId(other.getSenceId());
        }
        if (other.getNum() != 0) {
          setNum(other.getNum());
        }
        if (other.getState() != 0) {
          setState(other.getState());
        }
        if (typeBuilder_ == null) {
          if (!other.type_.isEmpty()) {
            if (type_.isEmpty()) {
              type_ = other.type_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTypeIsMutable();
              type_.addAll(other.type_);
            }
            onChanged();
          }
        } else {
          if (!other.type_.isEmpty()) {
            if (typeBuilder_.isEmpty()) {
              typeBuilder_.dispose();
              typeBuilder_ = null;
              type_ = other.type_;
              bitField0_ = (bitField0_ & ~0x00000001);
              typeBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTypeFieldBuilder() : null;
            } else {
              typeBuilder_.addAllMessages(other.type_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SenceEntity parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SenceEntity) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int senceId_ ;
      /**
       * <code>int32 senceId = 2;</code>
       */
      public int getSenceId() {
        return senceId_;
      }
      /**
       * <code>int32 senceId = 2;</code>
       */
      public Builder setSenceId(int value) {
        
        senceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 senceId = 2;</code>
       */
      public Builder clearSenceId() {
        
        senceId_ = 0;
        onChanged();
        return this;
      }

      private int num_ ;
      /**
       * <pre>
       *之后版本需要就去掉。。。
       * </pre>
       *
       * <code>int32 num = 3;</code>
       */
      public int getNum() {
        return num_;
      }
      /**
       * <pre>
       *之后版本需要就去掉。。。
       * </pre>
       *
       * <code>int32 num = 3;</code>
       */
      public Builder setNum(int value) {
        
        num_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *之后版本需要就去掉。。。
       * </pre>
       *
       * <code>int32 num = 3;</code>
       */
      public Builder clearNum() {
        
        num_ = 0;
        onChanged();
        return this;
      }

      private int state_ ;
      /**
       * <code>int32 state = 4;</code>
       */
      public int getState() {
        return state_;
      }
      /**
       * <code>int32 state = 4;</code>
       */
      public Builder setState(int value) {
        
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 state = 4;</code>
       */
      public Builder clearState() {
        
        state_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<EntityTypeProto.EntityType> type_ =
        java.util.Collections.emptyList();
      private void ensureTypeIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          type_ = new java.util.ArrayList<EntityTypeProto.EntityType>(type_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          EntityTypeProto.EntityType, EntityTypeProto.EntityType.Builder, EntityTypeProto.EntityTypeOrBuilder> typeBuilder_;

      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public java.util.List<EntityTypeProto.EntityType> getTypeList() {
        if (typeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(type_);
        } else {
          return typeBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public int getTypeCount() {
        if (typeBuilder_ == null) {
          return type_.size();
        } else {
          return typeBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public EntityTypeProto.EntityType getType(int index) {
        if (typeBuilder_ == null) {
          return type_.get(index);
        } else {
          return typeBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public Builder setType(
          int index, EntityTypeProto.EntityType value) {
        if (typeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTypeIsMutable();
          type_.set(index, value);
          onChanged();
        } else {
          typeBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public Builder setType(
          int index, EntityTypeProto.EntityType.Builder builderForValue) {
        if (typeBuilder_ == null) {
          ensureTypeIsMutable();
          type_.set(index, builderForValue.build());
          onChanged();
        } else {
          typeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public Builder addType(EntityTypeProto.EntityType value) {
        if (typeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTypeIsMutable();
          type_.add(value);
          onChanged();
        } else {
          typeBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public Builder addType(
          int index, EntityTypeProto.EntityType value) {
        if (typeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTypeIsMutable();
          type_.add(index, value);
          onChanged();
        } else {
          typeBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public Builder addType(
          EntityTypeProto.EntityType.Builder builderForValue) {
        if (typeBuilder_ == null) {
          ensureTypeIsMutable();
          type_.add(builderForValue.build());
          onChanged();
        } else {
          typeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public Builder addType(
          int index, EntityTypeProto.EntityType.Builder builderForValue) {
        if (typeBuilder_ == null) {
          ensureTypeIsMutable();
          type_.add(index, builderForValue.build());
          onChanged();
        } else {
          typeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public Builder addAllType(
          Iterable<? extends EntityTypeProto.EntityType> values) {
        if (typeBuilder_ == null) {
          ensureTypeIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, type_);
          onChanged();
        } else {
          typeBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public Builder clearType() {
        if (typeBuilder_ == null) {
          type_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          typeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public Builder removeType(int index) {
        if (typeBuilder_ == null) {
          ensureTypeIsMutable();
          type_.remove(index);
          onChanged();
        } else {
          typeBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public EntityTypeProto.EntityType.Builder getTypeBuilder(
          int index) {
        return getTypeFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public EntityTypeProto.EntityTypeOrBuilder getTypeOrBuilder(
          int index) {
        if (typeBuilder_ == null) {
          return type_.get(index);  } else {
          return typeBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public java.util.List<? extends EntityTypeProto.EntityTypeOrBuilder>
           getTypeOrBuilderList() {
        if (typeBuilder_ != null) {
          return typeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(type_);
        }
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public EntityTypeProto.EntityType.Builder addTypeBuilder() {
        return getTypeFieldBuilder().addBuilder(
            EntityTypeProto.EntityType.getDefaultInstance());
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public EntityTypeProto.EntityType.Builder addTypeBuilder(
          int index) {
        return getTypeFieldBuilder().addBuilder(
            index, EntityTypeProto.EntityType.getDefaultInstance());
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public java.util.List<EntityTypeProto.EntityType.Builder>
           getTypeBuilderList() {
        return getTypeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          EntityTypeProto.EntityType, EntityTypeProto.EntityType.Builder, EntityTypeProto.EntityTypeOrBuilder>
          getTypeFieldBuilder() {
        if (typeBuilder_ == null) {
          typeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              EntityTypeProto.EntityType, EntityTypeProto.EntityType.Builder, EntityTypeProto.EntityTypeOrBuilder>(
                  type_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          type_ = null;
        }
        return typeBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SenceEntity)
    }

    // @@protoc_insertion_point(class_scope:SenceEntity)
    private static final SenceEntity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SenceEntity();
    }

    public static SenceEntity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SenceEntity>
        PARSER = new com.google.protobuf.AbstractParser<SenceEntity>() {
      @Override
      public SenceEntity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SenceEntity(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SenceEntity> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SenceEntity> getParserForType() {
      return PARSER;
    }

    @Override
    public SenceEntity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RequestInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>uint64 msg_id = 1;</code>
     */
    long getMsgId();

    /**
     * <pre>
     *时间戳(单位:毫秒)
     * </pre>
     *
     * <code>uint64 time = 2;</code>
     */
    long getTime();

    /**
     * <code>int32 typeId = 3;</code>
     */
    int getTypeId();

    /**
     * <code>int32 senceId = 4;</code>
     */
    int getSenceId();
  }
  /**
   * <pre>
   *请求
   * </pre>
   *
   * Protobuf type {@code RequestInfo}
   */
  public  static final class RequestInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RequestInfo)
      RequestInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RequestInfo.newBuilder() to construct.
    private RequestInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestInfo() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new RequestInfo();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RequestInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              msgId_ = input.readUInt64();
              break;
            }
            case 16: {

              time_ = input.readUInt64();
              break;
            }
            case 24: {

              typeId_ = input.readInt32();
              break;
            }
            case 32: {

              senceId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SenceEntityProto.internal_static_RequestInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SenceEntityProto.internal_static_RequestInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RequestInfo.class, Builder.class);
    }

    public static final int MSG_ID_FIELD_NUMBER = 1;
    private long msgId_;
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>uint64 msg_id = 1;</code>
     */
    public long getMsgId() {
      return msgId_;
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private long time_;
    /**
     * <pre>
     *时间戳(单位:毫秒)
     * </pre>
     *
     * <code>uint64 time = 2;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int TYPEID_FIELD_NUMBER = 3;
    private int typeId_;
    /**
     * <code>int32 typeId = 3;</code>
     */
    public int getTypeId() {
      return typeId_;
    }

    public static final int SENCEID_FIELD_NUMBER = 4;
    private int senceId_;
    /**
     * <code>int32 senceId = 4;</code>
     */
    public int getSenceId() {
      return senceId_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgId_ != 0L) {
        output.writeUInt64(1, msgId_);
      }
      if (time_ != 0L) {
        output.writeUInt64(2, time_);
      }
      if (typeId_ != 0) {
        output.writeInt32(3, typeId_);
      }
      if (senceId_ != 0) {
        output.writeInt32(4, senceId_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, msgId_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, time_);
      }
      if (typeId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, typeId_);
      }
      if (senceId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, senceId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RequestInfo)) {
        return super.equals(obj);
      }
      RequestInfo other = (RequestInfo) obj;

      if (getMsgId()
          != other.getMsgId()) return false;
      if (getTime()
          != other.getTime()) return false;
      if (getTypeId()
          != other.getTypeId()) return false;
      if (getSenceId()
          != other.getSenceId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSG_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgId());
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (37 * hash) + TYPEID_FIELD_NUMBER;
      hash = (53 * hash) + getTypeId();
      hash = (37 * hash) + SENCEID_FIELD_NUMBER;
      hash = (53 * hash) + getSenceId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RequestInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RequestInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RequestInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RequestInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RequestInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RequestInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RequestInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *请求
     * </pre>
     *
     * Protobuf type {@code RequestInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestInfo)
        RequestInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SenceEntityProto.internal_static_RequestInfo_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SenceEntityProto.internal_static_RequestInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RequestInfo.class, Builder.class);
      }

      // Construct using org.sq.gameDemo.common.proto.SenceEntityProto.RequestInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        msgId_ = 0L;

        time_ = 0L;

        typeId_ = 0;

        senceId_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SenceEntityProto.internal_static_RequestInfo_descriptor;
      }

      @Override
      public RequestInfo getDefaultInstanceForType() {
        return RequestInfo.getDefaultInstance();
      }

      @Override
      public RequestInfo build() {
        RequestInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public RequestInfo buildPartial() {
        RequestInfo result = new RequestInfo(this);
        result.msgId_ = msgId_;
        result.time_ = time_;
        result.typeId_ = typeId_;
        result.senceId_ = senceId_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RequestInfo) {
          return mergeFrom((RequestInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RequestInfo other) {
        if (other == RequestInfo.getDefaultInstance()) return this;
        if (other.getMsgId() != 0L) {
          setMsgId(other.getMsgId());
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (other.getTypeId() != 0) {
          setTypeId(other.getTypeId());
        }
        if (other.getSenceId() != 0) {
          setSenceId(other.getSenceId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RequestInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RequestInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long msgId_ ;
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>uint64 msg_id = 1;</code>
       */
      public long getMsgId() {
        return msgId_;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>uint64 msg_id = 1;</code>
       */
      public Builder setMsgId(long value) {
        
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>uint64 msg_id = 1;</code>
       */
      public Builder clearMsgId() {
        
        msgId_ = 0L;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <pre>
       *时间戳(单位:毫秒)
       * </pre>
       *
       * <code>uint64 time = 2;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <pre>
       *时间戳(单位:毫秒)
       * </pre>
       *
       * <code>uint64 time = 2;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间戳(单位:毫秒)
       * </pre>
       *
       * <code>uint64 time = 2;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private int typeId_ ;
      /**
       * <code>int32 typeId = 3;</code>
       */
      public int getTypeId() {
        return typeId_;
      }
      /**
       * <code>int32 typeId = 3;</code>
       */
      public Builder setTypeId(int value) {
        
        typeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 typeId = 3;</code>
       */
      public Builder clearTypeId() {
        
        typeId_ = 0;
        onChanged();
        return this;
      }

      private int senceId_ ;
      /**
       * <code>int32 senceId = 4;</code>
       */
      public int getSenceId() {
        return senceId_;
      }
      /**
       * <code>int32 senceId = 4;</code>
       */
      public Builder setSenceId(int value) {
        
        senceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 senceId = 4;</code>
       */
      public Builder clearSenceId() {
        
        senceId_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RequestInfo)
    }

    // @@protoc_insertion_point(class_scope:RequestInfo)
    private static final RequestInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RequestInfo();
    }

    public static RequestInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestInfo>
        PARSER = new com.google.protobuf.AbstractParser<RequestInfo>() {
      @Override
      public RequestInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RequestInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public RequestInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResponseInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>uint64 msg_id = 1;</code>
     */
    long getMsgId();

    /**
     * <code>int32 result = 2;</code>
     */
    int getResult();

    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>uint64 time = 3;</code>
     */
    long getTime();

    /**
     * <code>string content = 4;</code>
     */
    String getContent();
    /**
     * <code>string content = 4;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>repeated .SenceEntity SenceEntity = 5;</code>
     */
    java.util.List<SenceEntity>
        getSenceEntityList();
    /**
     * <code>repeated .SenceEntity SenceEntity = 5;</code>
     */
    SenceEntity getSenceEntity(int index);
    /**
     * <code>repeated .SenceEntity SenceEntity = 5;</code>
     */
    int getSenceEntityCount();
    /**
     * <code>repeated .SenceEntity SenceEntity = 5;</code>
     */
    java.util.List<? extends SenceEntityOrBuilder>
        getSenceEntityOrBuilderList();
    /**
     * <code>repeated .SenceEntity SenceEntity = 5;</code>
     */
    SenceEntityOrBuilder getSenceEntityOrBuilder(
            int index);
  }
  /**
   * <pre>
   *响应
   * </pre>
   *
   * Protobuf type {@code ResponseInfo}
   */
  public  static final class ResponseInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ResponseInfo)
      ResponseInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResponseInfo.newBuilder() to construct.
    private ResponseInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseInfo() {
      content_ = "";
      senceEntity_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ResponseInfo();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              msgId_ = input.readUInt64();
              break;
            }
            case 16: {

              result_ = input.readInt32();
              break;
            }
            case 24: {

              time_ = input.readUInt64();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                senceEntity_ = new java.util.ArrayList<SenceEntity>();
                mutable_bitField0_ |= 0x00000001;
              }
              senceEntity_.add(
                  input.readMessage(SenceEntity.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          senceEntity_ = java.util.Collections.unmodifiableList(senceEntity_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SenceEntityProto.internal_static_ResponseInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SenceEntityProto.internal_static_ResponseInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ResponseInfo.class, Builder.class);
    }

    public static final int MSG_ID_FIELD_NUMBER = 1;
    private long msgId_;
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>uint64 msg_id = 1;</code>
     */
    public long getMsgId() {
      return msgId_;
    }

    public static final int RESULT_FIELD_NUMBER = 2;
    private int result_;
    /**
     * <code>int32 result = 2;</code>
     */
    public int getResult() {
      return result_;
    }

    public static final int TIME_FIELD_NUMBER = 3;
    private long time_;
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>uint64 time = 3;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    private volatile Object content_;
    /**
     * <code>string content = 4;</code>
     */
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 4;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENCEENTITY_FIELD_NUMBER = 5;
    private java.util.List<SenceEntity> senceEntity_;
    /**
     * <code>repeated .SenceEntity SenceEntity = 5;</code>
     */
    public java.util.List<SenceEntity> getSenceEntityList() {
      return senceEntity_;
    }
    /**
     * <code>repeated .SenceEntity SenceEntity = 5;</code>
     */
    public java.util.List<? extends SenceEntityOrBuilder>
        getSenceEntityOrBuilderList() {
      return senceEntity_;
    }
    /**
     * <code>repeated .SenceEntity SenceEntity = 5;</code>
     */
    public int getSenceEntityCount() {
      return senceEntity_.size();
    }
    /**
     * <code>repeated .SenceEntity SenceEntity = 5;</code>
     */
    public SenceEntity getSenceEntity(int index) {
      return senceEntity_.get(index);
    }
    /**
     * <code>repeated .SenceEntity SenceEntity = 5;</code>
     */
    public SenceEntityOrBuilder getSenceEntityOrBuilder(
        int index) {
      return senceEntity_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgId_ != 0L) {
        output.writeUInt64(1, msgId_);
      }
      if (result_ != 0) {
        output.writeInt32(2, result_);
      }
      if (time_ != 0L) {
        output.writeUInt64(3, time_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, content_);
      }
      for (int i = 0; i < senceEntity_.size(); i++) {
        output.writeMessage(5, senceEntity_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, msgId_);
      }
      if (result_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, result_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, time_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, content_);
      }
      for (int i = 0; i < senceEntity_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, senceEntity_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ResponseInfo)) {
        return super.equals(obj);
      }
      ResponseInfo other = (ResponseInfo) obj;

      if (getMsgId()
          != other.getMsgId()) return false;
      if (getResult()
          != other.getResult()) return false;
      if (getTime()
          != other.getTime()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!getSenceEntityList()
          .equals(other.getSenceEntityList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSG_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgId());
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      if (getSenceEntityCount() > 0) {
        hash = (37 * hash) + SENCEENTITY_FIELD_NUMBER;
        hash = (53 * hash) + getSenceEntityList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ResponseInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResponseInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResponseInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResponseInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResponseInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResponseInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResponseInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ResponseInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ResponseInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ResponseInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ResponseInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ResponseInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ResponseInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *响应
     * </pre>
     *
     * Protobuf type {@code ResponseInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResponseInfo)
        ResponseInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SenceEntityProto.internal_static_ResponseInfo_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SenceEntityProto.internal_static_ResponseInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ResponseInfo.class, Builder.class);
      }

      // Construct using org.sq.gameDemo.common.proto.SenceEntityProto.ResponseInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSenceEntityFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        msgId_ = 0L;

        result_ = 0;

        time_ = 0L;

        content_ = "";

        if (senceEntityBuilder_ == null) {
          senceEntity_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          senceEntityBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SenceEntityProto.internal_static_ResponseInfo_descriptor;
      }

      @Override
      public ResponseInfo getDefaultInstanceForType() {
        return ResponseInfo.getDefaultInstance();
      }

      @Override
      public ResponseInfo build() {
        ResponseInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ResponseInfo buildPartial() {
        ResponseInfo result = new ResponseInfo(this);
        int from_bitField0_ = bitField0_;
        result.msgId_ = msgId_;
        result.result_ = result_;
        result.time_ = time_;
        result.content_ = content_;
        if (senceEntityBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            senceEntity_ = java.util.Collections.unmodifiableList(senceEntity_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.senceEntity_ = senceEntity_;
        } else {
          result.senceEntity_ = senceEntityBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ResponseInfo) {
          return mergeFrom((ResponseInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ResponseInfo other) {
        if (other == ResponseInfo.getDefaultInstance()) return this;
        if (other.getMsgId() != 0L) {
          setMsgId(other.getMsgId());
        }
        if (other.getResult() != 0) {
          setResult(other.getResult());
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (senceEntityBuilder_ == null) {
          if (!other.senceEntity_.isEmpty()) {
            if (senceEntity_.isEmpty()) {
              senceEntity_ = other.senceEntity_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSenceEntityIsMutable();
              senceEntity_.addAll(other.senceEntity_);
            }
            onChanged();
          }
        } else {
          if (!other.senceEntity_.isEmpty()) {
            if (senceEntityBuilder_.isEmpty()) {
              senceEntityBuilder_.dispose();
              senceEntityBuilder_ = null;
              senceEntity_ = other.senceEntity_;
              bitField0_ = (bitField0_ & ~0x00000001);
              senceEntityBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSenceEntityFieldBuilder() : null;
            } else {
              senceEntityBuilder_.addAllMessages(other.senceEntity_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ResponseInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ResponseInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long msgId_ ;
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>uint64 msg_id = 1;</code>
       */
      public long getMsgId() {
        return msgId_;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>uint64 msg_id = 1;</code>
       */
      public Builder setMsgId(long value) {
        
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>uint64 msg_id = 1;</code>
       */
      public Builder clearMsgId() {
        
        msgId_ = 0L;
        onChanged();
        return this;
      }

      private int result_ ;
      /**
       * <code>int32 result = 2;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>int32 result = 2;</code>
       */
      public Builder setResult(int value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 result = 2;</code>
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>uint64 time = 3;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>uint64 time = 3;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>uint64 time = 3;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <code>string content = 4;</code>
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string content = 4;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 4;</code>
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 4;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 4;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private java.util.List<SenceEntity> senceEntity_ =
        java.util.Collections.emptyList();
      private void ensureSenceEntityIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          senceEntity_ = new java.util.ArrayList<SenceEntity>(senceEntity_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          SenceEntity, SenceEntity.Builder, SenceEntityOrBuilder> senceEntityBuilder_;

      /**
       * <code>repeated .SenceEntity SenceEntity = 5;</code>
       */
      public java.util.List<SenceEntity> getSenceEntityList() {
        if (senceEntityBuilder_ == null) {
          return java.util.Collections.unmodifiableList(senceEntity_);
        } else {
          return senceEntityBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .SenceEntity SenceEntity = 5;</code>
       */
      public int getSenceEntityCount() {
        if (senceEntityBuilder_ == null) {
          return senceEntity_.size();
        } else {
          return senceEntityBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .SenceEntity SenceEntity = 5;</code>
       */
      public SenceEntity getSenceEntity(int index) {
        if (senceEntityBuilder_ == null) {
          return senceEntity_.get(index);
        } else {
          return senceEntityBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .SenceEntity SenceEntity = 5;</code>
       */
      public Builder setSenceEntity(
          int index, SenceEntity value) {
        if (senceEntityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSenceEntityIsMutable();
          senceEntity_.set(index, value);
          onChanged();
        } else {
          senceEntityBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SenceEntity SenceEntity = 5;</code>
       */
      public Builder setSenceEntity(
          int index, SenceEntity.Builder builderForValue) {
        if (senceEntityBuilder_ == null) {
          ensureSenceEntityIsMutable();
          senceEntity_.set(index, builderForValue.build());
          onChanged();
        } else {
          senceEntityBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SenceEntity SenceEntity = 5;</code>
       */
      public Builder addSenceEntity(SenceEntity value) {
        if (senceEntityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSenceEntityIsMutable();
          senceEntity_.add(value);
          onChanged();
        } else {
          senceEntityBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .SenceEntity SenceEntity = 5;</code>
       */
      public Builder addSenceEntity(
          int index, SenceEntity value) {
        if (senceEntityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSenceEntityIsMutable();
          senceEntity_.add(index, value);
          onChanged();
        } else {
          senceEntityBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SenceEntity SenceEntity = 5;</code>
       */
      public Builder addSenceEntity(
          SenceEntity.Builder builderForValue) {
        if (senceEntityBuilder_ == null) {
          ensureSenceEntityIsMutable();
          senceEntity_.add(builderForValue.build());
          onChanged();
        } else {
          senceEntityBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SenceEntity SenceEntity = 5;</code>
       */
      public Builder addSenceEntity(
          int index, SenceEntity.Builder builderForValue) {
        if (senceEntityBuilder_ == null) {
          ensureSenceEntityIsMutable();
          senceEntity_.add(index, builderForValue.build());
          onChanged();
        } else {
          senceEntityBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SenceEntity SenceEntity = 5;</code>
       */
      public Builder addAllSenceEntity(
          Iterable<? extends SenceEntity> values) {
        if (senceEntityBuilder_ == null) {
          ensureSenceEntityIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, senceEntity_);
          onChanged();
        } else {
          senceEntityBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .SenceEntity SenceEntity = 5;</code>
       */
      public Builder clearSenceEntity() {
        if (senceEntityBuilder_ == null) {
          senceEntity_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          senceEntityBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .SenceEntity SenceEntity = 5;</code>
       */
      public Builder removeSenceEntity(int index) {
        if (senceEntityBuilder_ == null) {
          ensureSenceEntityIsMutable();
          senceEntity_.remove(index);
          onChanged();
        } else {
          senceEntityBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .SenceEntity SenceEntity = 5;</code>
       */
      public SenceEntity.Builder getSenceEntityBuilder(
          int index) {
        return getSenceEntityFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .SenceEntity SenceEntity = 5;</code>
       */
      public SenceEntityOrBuilder getSenceEntityOrBuilder(
          int index) {
        if (senceEntityBuilder_ == null) {
          return senceEntity_.get(index);  } else {
          return senceEntityBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .SenceEntity SenceEntity = 5;</code>
       */
      public java.util.List<? extends SenceEntityOrBuilder>
           getSenceEntityOrBuilderList() {
        if (senceEntityBuilder_ != null) {
          return senceEntityBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(senceEntity_);
        }
      }
      /**
       * <code>repeated .SenceEntity SenceEntity = 5;</code>
       */
      public SenceEntity.Builder addSenceEntityBuilder() {
        return getSenceEntityFieldBuilder().addBuilder(
            SenceEntity.getDefaultInstance());
      }
      /**
       * <code>repeated .SenceEntity SenceEntity = 5;</code>
       */
      public SenceEntity.Builder addSenceEntityBuilder(
          int index) {
        return getSenceEntityFieldBuilder().addBuilder(
            index, SenceEntity.getDefaultInstance());
      }
      /**
       * <code>repeated .SenceEntity SenceEntity = 5;</code>
       */
      public java.util.List<SenceEntity.Builder>
           getSenceEntityBuilderList() {
        return getSenceEntityFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          SenceEntity, SenceEntity.Builder, SenceEntityOrBuilder>
          getSenceEntityFieldBuilder() {
        if (senceEntityBuilder_ == null) {
          senceEntityBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              SenceEntity, SenceEntity.Builder, SenceEntityOrBuilder>(
                  senceEntity_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          senceEntity_ = null;
        }
        return senceEntityBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ResponseInfo)
    }

    // @@protoc_insertion_point(class_scope:ResponseInfo)
    private static final ResponseInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ResponseInfo();
    }

    public static ResponseInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseInfo>
        PARSER = new com.google.protobuf.AbstractParser<ResponseInfo>() {
      @Override
      public ResponseInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ResponseInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public ResponseInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SenceEntity_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SenceEntity_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021SenceEntity.proto\032\020EntityType.proto\"a\n" +
      "\013SenceEntity\022\n\n\002id\030\001 \001(\005\022\017\n\007senceId\030\002 \001(" +
      "\005\022\013\n\003num\030\003 \001(\005\022\r\n\005state\030\004 \001(\005\022\031\n\004type\030\005 " +
      "\003(\0132\013.EntityType\"L\n\013RequestInfo\022\016\n\006msg_i" +
      "d\030\001 \001(\004\022\014\n\004time\030\002 \001(\004\022\016\n\006typeId\030\003 \001(\005\022\017\n" +
      "\007senceId\030\004 \001(\005\"p\n\014ResponseInfo\022\016\n\006msg_id" +
      "\030\001 \001(\004\022\016\n\006result\030\002 \001(\005\022\014\n\004time\030\003 \001(\004\022\017\n\007" +
      "content\030\004 \001(\t\022!\n\013SenceEntity\030\005 \003(\0132\014.Sen" +
      "ceEntityB0\n\034org.sq.gameDemo.common.proto" +
      "B\020SenceEntityProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          EntityTypeProto.getDescriptor(),
        });
    internal_static_SenceEntity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SenceEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SenceEntity_descriptor,
        new String[] { "Id", "SenceId", "Num", "State", "Type", });
    internal_static_RequestInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RequestInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestInfo_descriptor,
        new String[] { "MsgId", "Time", "TypeId", "SenceId", });
    internal_static_ResponseInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ResponseInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseInfo_descriptor,
        new String[] { "MsgId", "Result", "Time", "Content", "SenceEntity", });
    EntityTypeProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
