// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Task.proto

package org.sq.gameDemo.common.proto;

public final class TaskPt {
  private TaskPt() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TaskOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Task)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>int32 taskId = 2;</code>
     */
    int getTaskId();

    /**
     * <code>string name = 3;</code>
     */
    String getName();
    /**
     * <code>string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 state = 4;</code>
     */
    int getState();

    /**
     * <code>string taskProgress = 5;</code>
     */
    String getTaskProgress();
    /**
     * <code>string taskProgress = 5;</code>
     */
    com.google.protobuf.ByteString
        getTaskProgressBytes();

    /**
     * <code>string description = 6;</code>
     */
    String getDescription();
    /**
     * <code>string description = 6;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>repeated .ItemInfo reward = 7;</code>
     */
    java.util.List<ItemInfoPt.ItemInfo>
        getRewardList();
    /**
     * <code>repeated .ItemInfo reward = 7;</code>
     */
    ItemInfoPt.ItemInfo getReward(int index);
    /**
     * <code>repeated .ItemInfo reward = 7;</code>
     */
    int getRewardCount();
    /**
     * <code>repeated .ItemInfo reward = 7;</code>
     */
    java.util.List<? extends ItemInfoPt.ItemInfoOrBuilder>
        getRewardOrBuilderList();
    /**
     * <code>repeated .ItemInfo reward = 7;</code>
     */
    ItemInfoPt.ItemInfoOrBuilder getRewardOrBuilder(
            int index);
  }
  /**
   * <pre>
   *实体类型
   * </pre>
   *
   * Protobuf type {@code Task}
   */
  public  static final class Task extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Task)
      TaskOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Task.newBuilder() to construct.
    private Task(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Task() {
      name_ = "";
      taskProgress_ = "";
      description_ = "";
      reward_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Task();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Task(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 16: {

              taskId_ = input.readInt32();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 32: {

              state_ = input.readInt32();
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              taskProgress_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                reward_ = new java.util.ArrayList<ItemInfoPt.ItemInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              reward_.add(
                  input.readMessage(ItemInfoPt.ItemInfo.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          reward_ = java.util.Collections.unmodifiableList(reward_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TaskPt.internal_static_Task_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TaskPt.internal_static_Task_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Task.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int TASKID_FIELD_NUMBER = 2;
    private int taskId_;
    /**
     * <code>int32 taskId = 2;</code>
     */
    public int getTaskId() {
      return taskId_;
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile Object name_;
    /**
     * <code>string name = 3;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATE_FIELD_NUMBER = 4;
    private int state_;
    /**
     * <code>int32 state = 4;</code>
     */
    public int getState() {
      return state_;
    }

    public static final int TASKPROGRESS_FIELD_NUMBER = 5;
    private volatile Object taskProgress_;
    /**
     * <code>string taskProgress = 5;</code>
     */
    public String getTaskProgress() {
      Object ref = taskProgress_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        taskProgress_ = s;
        return s;
      }
    }
    /**
     * <code>string taskProgress = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTaskProgressBytes() {
      Object ref = taskProgress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        taskProgress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 6;
    private volatile Object description_;
    /**
     * <code>string description = 6;</code>
     */
    public String getDescription() {
      Object ref = description_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REWARD_FIELD_NUMBER = 7;
    private java.util.List<ItemInfoPt.ItemInfo> reward_;
    /**
     * <code>repeated .ItemInfo reward = 7;</code>
     */
    public java.util.List<ItemInfoPt.ItemInfo> getRewardList() {
      return reward_;
    }
    /**
     * <code>repeated .ItemInfo reward = 7;</code>
     */
    public java.util.List<? extends ItemInfoPt.ItemInfoOrBuilder>
        getRewardOrBuilderList() {
      return reward_;
    }
    /**
     * <code>repeated .ItemInfo reward = 7;</code>
     */
    public int getRewardCount() {
      return reward_.size();
    }
    /**
     * <code>repeated .ItemInfo reward = 7;</code>
     */
    public ItemInfoPt.ItemInfo getReward(int index) {
      return reward_.get(index);
    }
    /**
     * <code>repeated .ItemInfo reward = 7;</code>
     */
    public ItemInfoPt.ItemInfoOrBuilder getRewardOrBuilder(
        int index) {
      return reward_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (taskId_ != 0) {
        output.writeInt32(2, taskId_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (state_ != 0) {
        output.writeInt32(4, state_);
      }
      if (!getTaskProgressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, taskProgress_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, description_);
      }
      for (int i = 0; i < reward_.size(); i++) {
        output.writeMessage(7, reward_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (taskId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, taskId_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (state_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, state_);
      }
      if (!getTaskProgressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, taskProgress_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, description_);
      }
      for (int i = 0; i < reward_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, reward_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Task)) {
        return super.equals(obj);
      }
      Task other = (Task) obj;

      if (getId()
          != other.getId()) return false;
      if (getTaskId()
          != other.getTaskId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getState()
          != other.getState()) return false;
      if (!getTaskProgress()
          .equals(other.getTaskProgress())) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (!getRewardList()
          .equals(other.getRewardList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + TASKID_FIELD_NUMBER;
      hash = (53 * hash) + getTaskId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + getState();
      hash = (37 * hash) + TASKPROGRESS_FIELD_NUMBER;
      hash = (53 * hash) + getTaskProgress().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      if (getRewardCount() > 0) {
        hash = (37 * hash) + REWARD_FIELD_NUMBER;
        hash = (53 * hash) + getRewardList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Task parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Task parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Task parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Task parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Task parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Task parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Task parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Task parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Task parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Task parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Task parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Task parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Task prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *实体类型
     * </pre>
     *
     * Protobuf type {@code Task}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Task)
        TaskOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TaskPt.internal_static_Task_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TaskPt.internal_static_Task_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Task.class, Builder.class);
      }

      // Construct using org.sq.gameDemo.common.proto.TaskPt.Task.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRewardFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        taskId_ = 0;

        name_ = "";

        state_ = 0;

        taskProgress_ = "";

        description_ = "";

        if (rewardBuilder_ == null) {
          reward_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          rewardBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TaskPt.internal_static_Task_descriptor;
      }

      @Override
      public Task getDefaultInstanceForType() {
        return Task.getDefaultInstance();
      }

      @Override
      public Task build() {
        Task result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Task buildPartial() {
        Task result = new Task(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.taskId_ = taskId_;
        result.name_ = name_;
        result.state_ = state_;
        result.taskProgress_ = taskProgress_;
        result.description_ = description_;
        if (rewardBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            reward_ = java.util.Collections.unmodifiableList(reward_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.reward_ = reward_;
        } else {
          result.reward_ = rewardBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Task) {
          return mergeFrom((Task)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Task other) {
        if (other == Task.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getTaskId() != 0) {
          setTaskId(other.getTaskId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getState() != 0) {
          setState(other.getState());
        }
        if (!other.getTaskProgress().isEmpty()) {
          taskProgress_ = other.taskProgress_;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (rewardBuilder_ == null) {
          if (!other.reward_.isEmpty()) {
            if (reward_.isEmpty()) {
              reward_ = other.reward_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRewardIsMutable();
              reward_.addAll(other.reward_);
            }
            onChanged();
          }
        } else {
          if (!other.reward_.isEmpty()) {
            if (rewardBuilder_.isEmpty()) {
              rewardBuilder_.dispose();
              rewardBuilder_ = null;
              reward_ = other.reward_;
              bitField0_ = (bitField0_ & ~0x00000001);
              rewardBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRewardFieldBuilder() : null;
            } else {
              rewardBuilder_.addAllMessages(other.reward_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Task parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Task) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int taskId_ ;
      /**
       * <code>int32 taskId = 2;</code>
       */
      public int getTaskId() {
        return taskId_;
      }
      /**
       * <code>int32 taskId = 2;</code>
       */
      public Builder setTaskId(int value) {
        
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 taskId = 2;</code>
       */
      public Builder clearTaskId() {
        
        taskId_ = 0;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>string name = 3;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int state_ ;
      /**
       * <code>int32 state = 4;</code>
       */
      public int getState() {
        return state_;
      }
      /**
       * <code>int32 state = 4;</code>
       */
      public Builder setState(int value) {
        
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 state = 4;</code>
       */
      public Builder clearState() {
        
        state_ = 0;
        onChanged();
        return this;
      }

      private Object taskProgress_ = "";
      /**
       * <code>string taskProgress = 5;</code>
       */
      public String getTaskProgress() {
        Object ref = taskProgress_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          taskProgress_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string taskProgress = 5;</code>
       */
      public com.google.protobuf.ByteString
          getTaskProgressBytes() {
        Object ref = taskProgress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          taskProgress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string taskProgress = 5;</code>
       */
      public Builder setTaskProgress(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskProgress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string taskProgress = 5;</code>
       */
      public Builder clearTaskProgress() {
        
        taskProgress_ = getDefaultInstance().getTaskProgress();
        onChanged();
        return this;
      }
      /**
       * <code>string taskProgress = 5;</code>
       */
      public Builder setTaskProgressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        taskProgress_ = value;
        onChanged();
        return this;
      }

      private Object description_ = "";
      /**
       * <code>string description = 6;</code>
       */
      public String getDescription() {
        Object ref = description_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string description = 6;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 6;</code>
       */
      public Builder setDescription(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 6;</code>
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 6;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private java.util.List<ItemInfoPt.ItemInfo> reward_ =
        java.util.Collections.emptyList();
      private void ensureRewardIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          reward_ = new java.util.ArrayList<ItemInfoPt.ItemInfo>(reward_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ItemInfoPt.ItemInfo, ItemInfoPt.ItemInfo.Builder, ItemInfoPt.ItemInfoOrBuilder> rewardBuilder_;

      /**
       * <code>repeated .ItemInfo reward = 7;</code>
       */
      public java.util.List<ItemInfoPt.ItemInfo> getRewardList() {
        if (rewardBuilder_ == null) {
          return java.util.Collections.unmodifiableList(reward_);
        } else {
          return rewardBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ItemInfo reward = 7;</code>
       */
      public int getRewardCount() {
        if (rewardBuilder_ == null) {
          return reward_.size();
        } else {
          return rewardBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ItemInfo reward = 7;</code>
       */
      public ItemInfoPt.ItemInfo getReward(int index) {
        if (rewardBuilder_ == null) {
          return reward_.get(index);
        } else {
          return rewardBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ItemInfo reward = 7;</code>
       */
      public Builder setReward(
          int index, ItemInfoPt.ItemInfo value) {
        if (rewardBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRewardIsMutable();
          reward_.set(index, value);
          onChanged();
        } else {
          rewardBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ItemInfo reward = 7;</code>
       */
      public Builder setReward(
          int index, ItemInfoPt.ItemInfo.Builder builderForValue) {
        if (rewardBuilder_ == null) {
          ensureRewardIsMutable();
          reward_.set(index, builderForValue.build());
          onChanged();
        } else {
          rewardBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ItemInfo reward = 7;</code>
       */
      public Builder addReward(ItemInfoPt.ItemInfo value) {
        if (rewardBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRewardIsMutable();
          reward_.add(value);
          onChanged();
        } else {
          rewardBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ItemInfo reward = 7;</code>
       */
      public Builder addReward(
          int index, ItemInfoPt.ItemInfo value) {
        if (rewardBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRewardIsMutable();
          reward_.add(index, value);
          onChanged();
        } else {
          rewardBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ItemInfo reward = 7;</code>
       */
      public Builder addReward(
          ItemInfoPt.ItemInfo.Builder builderForValue) {
        if (rewardBuilder_ == null) {
          ensureRewardIsMutable();
          reward_.add(builderForValue.build());
          onChanged();
        } else {
          rewardBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ItemInfo reward = 7;</code>
       */
      public Builder addReward(
          int index, ItemInfoPt.ItemInfo.Builder builderForValue) {
        if (rewardBuilder_ == null) {
          ensureRewardIsMutable();
          reward_.add(index, builderForValue.build());
          onChanged();
        } else {
          rewardBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ItemInfo reward = 7;</code>
       */
      public Builder addAllReward(
          Iterable<? extends ItemInfoPt.ItemInfo> values) {
        if (rewardBuilder_ == null) {
          ensureRewardIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, reward_);
          onChanged();
        } else {
          rewardBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ItemInfo reward = 7;</code>
       */
      public Builder clearReward() {
        if (rewardBuilder_ == null) {
          reward_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          rewardBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ItemInfo reward = 7;</code>
       */
      public Builder removeReward(int index) {
        if (rewardBuilder_ == null) {
          ensureRewardIsMutable();
          reward_.remove(index);
          onChanged();
        } else {
          rewardBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ItemInfo reward = 7;</code>
       */
      public ItemInfoPt.ItemInfo.Builder getRewardBuilder(
          int index) {
        return getRewardFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ItemInfo reward = 7;</code>
       */
      public ItemInfoPt.ItemInfoOrBuilder getRewardOrBuilder(
          int index) {
        if (rewardBuilder_ == null) {
          return reward_.get(index);  } else {
          return rewardBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ItemInfo reward = 7;</code>
       */
      public java.util.List<? extends ItemInfoPt.ItemInfoOrBuilder>
           getRewardOrBuilderList() {
        if (rewardBuilder_ != null) {
          return rewardBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(reward_);
        }
      }
      /**
       * <code>repeated .ItemInfo reward = 7;</code>
       */
      public ItemInfoPt.ItemInfo.Builder addRewardBuilder() {
        return getRewardFieldBuilder().addBuilder(
            ItemInfoPt.ItemInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .ItemInfo reward = 7;</code>
       */
      public ItemInfoPt.ItemInfo.Builder addRewardBuilder(
          int index) {
        return getRewardFieldBuilder().addBuilder(
            index, ItemInfoPt.ItemInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .ItemInfo reward = 7;</code>
       */
      public java.util.List<ItemInfoPt.ItemInfo.Builder>
           getRewardBuilderList() {
        return getRewardFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ItemInfoPt.ItemInfo, ItemInfoPt.ItemInfo.Builder, ItemInfoPt.ItemInfoOrBuilder>
          getRewardFieldBuilder() {
        if (rewardBuilder_ == null) {
          rewardBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ItemInfoPt.ItemInfo, ItemInfoPt.ItemInfo.Builder, ItemInfoPt.ItemInfoOrBuilder>(
                  reward_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          reward_ = null;
        }
        return rewardBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Task)
    }

    // @@protoc_insertion_point(class_scope:Task)
    private static final Task DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Task();
    }

    public static Task getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Task>
        PARSER = new com.google.protobuf.AbstractParser<Task>() {
      @Override
      public Task parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Task(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Task> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Task> getParserForType() {
      return PARSER;
    }

    @Override
    public Task getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TaskRequestInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TaskRequestInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>uint64 msg_id = 1;</code>
     */
    long getMsgId();

    /**
     * <pre>
     *时间戳(单位:毫秒)
     * </pre>
     *
     * <code>uint64 time = 2;</code>
     */
    long getTime();

    /**
     * <pre>
     *获取全部写-1
     * </pre>
     *
     * <code>int32 taskId = 3;</code>
     */
    int getTaskId();

    /**
     * <code>string name = 4;</code>
     */
    String getName();
    /**
     * <code>string name = 4;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * <pre>
   *请求
   * </pre>
   *
   * Protobuf type {@code TaskRequestInfo}
   */
  public  static final class TaskRequestInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TaskRequestInfo)
      TaskRequestInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TaskRequestInfo.newBuilder() to construct.
    private TaskRequestInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TaskRequestInfo() {
      name_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new TaskRequestInfo();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TaskRequestInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              msgId_ = input.readUInt64();
              break;
            }
            case 16: {

              time_ = input.readUInt64();
              break;
            }
            case 24: {

              taskId_ = input.readInt32();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TaskPt.internal_static_TaskRequestInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TaskPt.internal_static_TaskRequestInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TaskRequestInfo.class, Builder.class);
    }

    public static final int MSG_ID_FIELD_NUMBER = 1;
    private long msgId_;
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>uint64 msg_id = 1;</code>
     */
    public long getMsgId() {
      return msgId_;
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private long time_;
    /**
     * <pre>
     *时间戳(单位:毫秒)
     * </pre>
     *
     * <code>uint64 time = 2;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int TASKID_FIELD_NUMBER = 3;
    private int taskId_;
    /**
     * <pre>
     *获取全部写-1
     * </pre>
     *
     * <code>int32 taskId = 3;</code>
     */
    public int getTaskId() {
      return taskId_;
    }

    public static final int NAME_FIELD_NUMBER = 4;
    private volatile Object name_;
    /**
     * <code>string name = 4;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgId_ != 0L) {
        output.writeUInt64(1, msgId_);
      }
      if (time_ != 0L) {
        output.writeUInt64(2, time_);
      }
      if (taskId_ != 0) {
        output.writeInt32(3, taskId_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, name_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, msgId_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, time_);
      }
      if (taskId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, taskId_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TaskRequestInfo)) {
        return super.equals(obj);
      }
      TaskRequestInfo other = (TaskRequestInfo) obj;

      if (getMsgId()
          != other.getMsgId()) return false;
      if (getTime()
          != other.getTime()) return false;
      if (getTaskId()
          != other.getTaskId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSG_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgId());
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (37 * hash) + TASKID_FIELD_NUMBER;
      hash = (53 * hash) + getTaskId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TaskRequestInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TaskRequestInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TaskRequestInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TaskRequestInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TaskRequestInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TaskRequestInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TaskRequestInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TaskRequestInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TaskRequestInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TaskRequestInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TaskRequestInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TaskRequestInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TaskRequestInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *请求
     * </pre>
     *
     * Protobuf type {@code TaskRequestInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TaskRequestInfo)
        TaskRequestInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TaskPt.internal_static_TaskRequestInfo_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TaskPt.internal_static_TaskRequestInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TaskRequestInfo.class, Builder.class);
      }

      // Construct using org.sq.gameDemo.common.proto.TaskPt.TaskRequestInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        msgId_ = 0L;

        time_ = 0L;

        taskId_ = 0;

        name_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TaskPt.internal_static_TaskRequestInfo_descriptor;
      }

      @Override
      public TaskRequestInfo getDefaultInstanceForType() {
        return TaskRequestInfo.getDefaultInstance();
      }

      @Override
      public TaskRequestInfo build() {
        TaskRequestInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public TaskRequestInfo buildPartial() {
        TaskRequestInfo result = new TaskRequestInfo(this);
        result.msgId_ = msgId_;
        result.time_ = time_;
        result.taskId_ = taskId_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TaskRequestInfo) {
          return mergeFrom((TaskRequestInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TaskRequestInfo other) {
        if (other == TaskRequestInfo.getDefaultInstance()) return this;
        if (other.getMsgId() != 0L) {
          setMsgId(other.getMsgId());
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (other.getTaskId() != 0) {
          setTaskId(other.getTaskId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TaskRequestInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TaskRequestInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long msgId_ ;
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>uint64 msg_id = 1;</code>
       */
      public long getMsgId() {
        return msgId_;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>uint64 msg_id = 1;</code>
       */
      public Builder setMsgId(long value) {
        
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>uint64 msg_id = 1;</code>
       */
      public Builder clearMsgId() {
        
        msgId_ = 0L;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <pre>
       *时间戳(单位:毫秒)
       * </pre>
       *
       * <code>uint64 time = 2;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <pre>
       *时间戳(单位:毫秒)
       * </pre>
       *
       * <code>uint64 time = 2;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间戳(单位:毫秒)
       * </pre>
       *
       * <code>uint64 time = 2;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private int taskId_ ;
      /**
       * <pre>
       *获取全部写-1
       * </pre>
       *
       * <code>int32 taskId = 3;</code>
       */
      public int getTaskId() {
        return taskId_;
      }
      /**
       * <pre>
       *获取全部写-1
       * </pre>
       *
       * <code>int32 taskId = 3;</code>
       */
      public Builder setTaskId(int value) {
        
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *获取全部写-1
       * </pre>
       *
       * <code>int32 taskId = 3;</code>
       */
      public Builder clearTaskId() {
        
        taskId_ = 0;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>string name = 4;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 4;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 4;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 4;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TaskRequestInfo)
    }

    // @@protoc_insertion_point(class_scope:TaskRequestInfo)
    private static final TaskRequestInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TaskRequestInfo();
    }

    public static TaskRequestInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TaskRequestInfo>
        PARSER = new com.google.protobuf.AbstractParser<TaskRequestInfo>() {
      @Override
      public TaskRequestInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TaskRequestInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TaskRequestInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TaskRequestInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public TaskRequestInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TaskResponseInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TaskResponseInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>uint64 msg_id = 1;</code>
     */
    long getMsgId();

    /**
     * <code>int32 result = 2;</code>
     */
    int getResult();

    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>uint64 time = 3;</code>
     */
    long getTime();

    /**
     * <code>string content = 4;</code>
     */
    String getContent();
    /**
     * <code>string content = 4;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>repeated .Task task = 5;</code>
     */
    java.util.List<Task>
        getTaskList();
    /**
     * <code>repeated .Task task = 5;</code>
     */
    Task getTask(int index);
    /**
     * <code>repeated .Task task = 5;</code>
     */
    int getTaskCount();
    /**
     * <code>repeated .Task task = 5;</code>
     */
    java.util.List<? extends TaskOrBuilder>
        getTaskOrBuilderList();
    /**
     * <code>repeated .Task task = 5;</code>
     */
    TaskOrBuilder getTaskOrBuilder(
            int index);
  }
  /**
   * <pre>
   *响应
   * </pre>
   *
   * Protobuf type {@code TaskResponseInfo}
   */
  public  static final class TaskResponseInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TaskResponseInfo)
      TaskResponseInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TaskResponseInfo.newBuilder() to construct.
    private TaskResponseInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TaskResponseInfo() {
      content_ = "";
      task_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new TaskResponseInfo();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TaskResponseInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              msgId_ = input.readUInt64();
              break;
            }
            case 16: {

              result_ = input.readInt32();
              break;
            }
            case 24: {

              time_ = input.readUInt64();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                task_ = new java.util.ArrayList<Task>();
                mutable_bitField0_ |= 0x00000001;
              }
              task_.add(
                  input.readMessage(Task.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          task_ = java.util.Collections.unmodifiableList(task_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TaskPt.internal_static_TaskResponseInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TaskPt.internal_static_TaskResponseInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TaskResponseInfo.class, Builder.class);
    }

    public static final int MSG_ID_FIELD_NUMBER = 1;
    private long msgId_;
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>uint64 msg_id = 1;</code>
     */
    public long getMsgId() {
      return msgId_;
    }

    public static final int RESULT_FIELD_NUMBER = 2;
    private int result_;
    /**
     * <code>int32 result = 2;</code>
     */
    public int getResult() {
      return result_;
    }

    public static final int TIME_FIELD_NUMBER = 3;
    private long time_;
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>uint64 time = 3;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    private volatile Object content_;
    /**
     * <code>string content = 4;</code>
     */
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 4;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TASK_FIELD_NUMBER = 5;
    private java.util.List<Task> task_;
    /**
     * <code>repeated .Task task = 5;</code>
     */
    public java.util.List<Task> getTaskList() {
      return task_;
    }
    /**
     * <code>repeated .Task task = 5;</code>
     */
    public java.util.List<? extends TaskOrBuilder>
        getTaskOrBuilderList() {
      return task_;
    }
    /**
     * <code>repeated .Task task = 5;</code>
     */
    public int getTaskCount() {
      return task_.size();
    }
    /**
     * <code>repeated .Task task = 5;</code>
     */
    public Task getTask(int index) {
      return task_.get(index);
    }
    /**
     * <code>repeated .Task task = 5;</code>
     */
    public TaskOrBuilder getTaskOrBuilder(
        int index) {
      return task_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgId_ != 0L) {
        output.writeUInt64(1, msgId_);
      }
      if (result_ != 0) {
        output.writeInt32(2, result_);
      }
      if (time_ != 0L) {
        output.writeUInt64(3, time_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, content_);
      }
      for (int i = 0; i < task_.size(); i++) {
        output.writeMessage(5, task_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, msgId_);
      }
      if (result_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, result_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, time_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, content_);
      }
      for (int i = 0; i < task_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, task_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TaskResponseInfo)) {
        return super.equals(obj);
      }
      TaskResponseInfo other = (TaskResponseInfo) obj;

      if (getMsgId()
          != other.getMsgId()) return false;
      if (getResult()
          != other.getResult()) return false;
      if (getTime()
          != other.getTime()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!getTaskList()
          .equals(other.getTaskList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSG_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgId());
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      if (getTaskCount() > 0) {
        hash = (37 * hash) + TASK_FIELD_NUMBER;
        hash = (53 * hash) + getTaskList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TaskResponseInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TaskResponseInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TaskResponseInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TaskResponseInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TaskResponseInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TaskResponseInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TaskResponseInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TaskResponseInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TaskResponseInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TaskResponseInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TaskResponseInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TaskResponseInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TaskResponseInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *响应
     * </pre>
     *
     * Protobuf type {@code TaskResponseInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TaskResponseInfo)
        TaskResponseInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TaskPt.internal_static_TaskResponseInfo_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TaskPt.internal_static_TaskResponseInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TaskResponseInfo.class, Builder.class);
      }

      // Construct using org.sq.gameDemo.common.proto.TaskPt.TaskResponseInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTaskFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        msgId_ = 0L;

        result_ = 0;

        time_ = 0L;

        content_ = "";

        if (taskBuilder_ == null) {
          task_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          taskBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TaskPt.internal_static_TaskResponseInfo_descriptor;
      }

      @Override
      public TaskResponseInfo getDefaultInstanceForType() {
        return TaskResponseInfo.getDefaultInstance();
      }

      @Override
      public TaskResponseInfo build() {
        TaskResponseInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public TaskResponseInfo buildPartial() {
        TaskResponseInfo result = new TaskResponseInfo(this);
        int from_bitField0_ = bitField0_;
        result.msgId_ = msgId_;
        result.result_ = result_;
        result.time_ = time_;
        result.content_ = content_;
        if (taskBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            task_ = java.util.Collections.unmodifiableList(task_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.task_ = task_;
        } else {
          result.task_ = taskBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TaskResponseInfo) {
          return mergeFrom((TaskResponseInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TaskResponseInfo other) {
        if (other == TaskResponseInfo.getDefaultInstance()) return this;
        if (other.getMsgId() != 0L) {
          setMsgId(other.getMsgId());
        }
        if (other.getResult() != 0) {
          setResult(other.getResult());
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (taskBuilder_ == null) {
          if (!other.task_.isEmpty()) {
            if (task_.isEmpty()) {
              task_ = other.task_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTaskIsMutable();
              task_.addAll(other.task_);
            }
            onChanged();
          }
        } else {
          if (!other.task_.isEmpty()) {
            if (taskBuilder_.isEmpty()) {
              taskBuilder_.dispose();
              taskBuilder_ = null;
              task_ = other.task_;
              bitField0_ = (bitField0_ & ~0x00000001);
              taskBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTaskFieldBuilder() : null;
            } else {
              taskBuilder_.addAllMessages(other.task_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TaskResponseInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TaskResponseInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long msgId_ ;
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>uint64 msg_id = 1;</code>
       */
      public long getMsgId() {
        return msgId_;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>uint64 msg_id = 1;</code>
       */
      public Builder setMsgId(long value) {
        
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>uint64 msg_id = 1;</code>
       */
      public Builder clearMsgId() {
        
        msgId_ = 0L;
        onChanged();
        return this;
      }

      private int result_ ;
      /**
       * <code>int32 result = 2;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>int32 result = 2;</code>
       */
      public Builder setResult(int value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 result = 2;</code>
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>uint64 time = 3;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>uint64 time = 3;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>uint64 time = 3;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <code>string content = 4;</code>
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string content = 4;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 4;</code>
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 4;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 4;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private java.util.List<Task> task_ =
        java.util.Collections.emptyList();
      private void ensureTaskIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          task_ = new java.util.ArrayList<Task>(task_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Task, Task.Builder, TaskOrBuilder> taskBuilder_;

      /**
       * <code>repeated .Task task = 5;</code>
       */
      public java.util.List<Task> getTaskList() {
        if (taskBuilder_ == null) {
          return java.util.Collections.unmodifiableList(task_);
        } else {
          return taskBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Task task = 5;</code>
       */
      public int getTaskCount() {
        if (taskBuilder_ == null) {
          return task_.size();
        } else {
          return taskBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Task task = 5;</code>
       */
      public Task getTask(int index) {
        if (taskBuilder_ == null) {
          return task_.get(index);
        } else {
          return taskBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Task task = 5;</code>
       */
      public Builder setTask(
          int index, Task value) {
        if (taskBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTaskIsMutable();
          task_.set(index, value);
          onChanged();
        } else {
          taskBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Task task = 5;</code>
       */
      public Builder setTask(
          int index, Task.Builder builderForValue) {
        if (taskBuilder_ == null) {
          ensureTaskIsMutable();
          task_.set(index, builderForValue.build());
          onChanged();
        } else {
          taskBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Task task = 5;</code>
       */
      public Builder addTask(Task value) {
        if (taskBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTaskIsMutable();
          task_.add(value);
          onChanged();
        } else {
          taskBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Task task = 5;</code>
       */
      public Builder addTask(
          int index, Task value) {
        if (taskBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTaskIsMutable();
          task_.add(index, value);
          onChanged();
        } else {
          taskBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Task task = 5;</code>
       */
      public Builder addTask(
          Task.Builder builderForValue) {
        if (taskBuilder_ == null) {
          ensureTaskIsMutable();
          task_.add(builderForValue.build());
          onChanged();
        } else {
          taskBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Task task = 5;</code>
       */
      public Builder addTask(
          int index, Task.Builder builderForValue) {
        if (taskBuilder_ == null) {
          ensureTaskIsMutable();
          task_.add(index, builderForValue.build());
          onChanged();
        } else {
          taskBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Task task = 5;</code>
       */
      public Builder addAllTask(
          Iterable<? extends Task> values) {
        if (taskBuilder_ == null) {
          ensureTaskIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, task_);
          onChanged();
        } else {
          taskBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Task task = 5;</code>
       */
      public Builder clearTask() {
        if (taskBuilder_ == null) {
          task_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          taskBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Task task = 5;</code>
       */
      public Builder removeTask(int index) {
        if (taskBuilder_ == null) {
          ensureTaskIsMutable();
          task_.remove(index);
          onChanged();
        } else {
          taskBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Task task = 5;</code>
       */
      public Task.Builder getTaskBuilder(
          int index) {
        return getTaskFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Task task = 5;</code>
       */
      public TaskOrBuilder getTaskOrBuilder(
          int index) {
        if (taskBuilder_ == null) {
          return task_.get(index);  } else {
          return taskBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Task task = 5;</code>
       */
      public java.util.List<? extends TaskOrBuilder>
           getTaskOrBuilderList() {
        if (taskBuilder_ != null) {
          return taskBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(task_);
        }
      }
      /**
       * <code>repeated .Task task = 5;</code>
       */
      public Task.Builder addTaskBuilder() {
        return getTaskFieldBuilder().addBuilder(
            Task.getDefaultInstance());
      }
      /**
       * <code>repeated .Task task = 5;</code>
       */
      public Task.Builder addTaskBuilder(
          int index) {
        return getTaskFieldBuilder().addBuilder(
            index, Task.getDefaultInstance());
      }
      /**
       * <code>repeated .Task task = 5;</code>
       */
      public java.util.List<Task.Builder>
           getTaskBuilderList() {
        return getTaskFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Task, Task.Builder, TaskOrBuilder>
          getTaskFieldBuilder() {
        if (taskBuilder_ == null) {
          taskBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Task, Task.Builder, TaskOrBuilder>(
                  task_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          task_ = null;
        }
        return taskBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TaskResponseInfo)
    }

    // @@protoc_insertion_point(class_scope:TaskResponseInfo)
    private static final TaskResponseInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TaskResponseInfo();
    }

    public static TaskResponseInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TaskResponseInfo>
        PARSER = new com.google.protobuf.AbstractParser<TaskResponseInfo>() {
      @Override
      public TaskResponseInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TaskResponseInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TaskResponseInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TaskResponseInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public TaskResponseInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Task_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Task_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TaskRequestInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TaskRequestInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TaskResponseInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TaskResponseInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nTask.proto\032\016ItemInfo.proto\"\205\001\n\004Task\022\n\n" +
      "\002id\030\001 \001(\005\022\016\n\006taskId\030\002 \001(\005\022\014\n\004name\030\003 \001(\t\022" +
      "\r\n\005state\030\004 \001(\005\022\024\n\014taskProgress\030\005 \001(\t\022\023\n\013" +
      "description\030\006 \001(\t\022\031\n\006reward\030\007 \003(\0132\t.Item" +
      "Info\"M\n\017TaskRequestInfo\022\016\n\006msg_id\030\001 \001(\004\022" +
      "\014\n\004time\030\002 \001(\004\022\016\n\006taskId\030\003 \001(\005\022\014\n\004name\030\004 " +
      "\001(\t\"f\n\020TaskResponseInfo\022\016\n\006msg_id\030\001 \001(\004\022" +
      "\016\n\006result\030\002 \001(\005\022\014\n\004time\030\003 \001(\004\022\017\n\007content" +
      "\030\004 \001(\t\022\023\n\004task\030\005 \003(\0132\005.TaskB&\n\034org.sq.ga" +
      "meDemo.common.protoB\006TaskPtb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ItemInfoPt.getDescriptor(),
        });
    internal_static_Task_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Task_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Task_descriptor,
        new String[] { "Id", "TaskId", "Name", "State", "TaskProgress", "Description", "Reward", });
    internal_static_TaskRequestInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TaskRequestInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TaskRequestInfo_descriptor,
        new String[] { "MsgId", "Time", "TaskId", "Name", });
    internal_static_TaskResponseInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_TaskResponseInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TaskResponseInfo_descriptor,
        new String[] { "MsgId", "Result", "Time", "Content", "Task", });
    ItemInfoPt.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
