// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserEntity.proto

package org.sq.gameDemo.common.proto;

public final class UserEntityProto {
  private UserEntityProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserEntityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserEntity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 id = 1;</code>
     */
    long getId();

    /**
     * <code>string name = 2;</code>
     */
    String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 userId = 3;</code>
     */
    int getUserId();

    /**
     * <code>int32 state = 4;</code>
     */
    int getState();

    /**
     * <code>int32 typeId = 5;</code>
     */
    int getTypeId();

    /**
     * <code>int32 senceId = 6;</code>
     */
    int getSenceId();

    /**
     * <code>int32 exp = 7;</code>
     */
    int getExp();
  }
  /**
   * <pre>
   *用户角色实体
   * </pre>
   *
   * Protobuf type {@code UserEntity}
   */
  public  static final class UserEntity extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UserEntity)
      UserEntityOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserEntity.newBuilder() to construct.
    private UserEntity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserEntity() {
      name_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserEntity();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserEntity(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readUInt64();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              userId_ = input.readInt32();
              break;
            }
            case 32: {

              state_ = input.readInt32();
              break;
            }
            case 40: {

              typeId_ = input.readInt32();
              break;
            }
            case 48: {

              senceId_ = input.readInt32();
              break;
            }
            case 56: {

              exp_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserEntityProto.internal_static_UserEntity_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserEntityProto.internal_static_UserEntity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UserEntity.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>uint64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 3;
    private int userId_;
    /**
     * <code>int32 userId = 3;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int STATE_FIELD_NUMBER = 4;
    private int state_;
    /**
     * <code>int32 state = 4;</code>
     */
    public int getState() {
      return state_;
    }

    public static final int TYPEID_FIELD_NUMBER = 5;
    private int typeId_;
    /**
     * <code>int32 typeId = 5;</code>
     */
    public int getTypeId() {
      return typeId_;
    }

    public static final int SENCEID_FIELD_NUMBER = 6;
    private int senceId_;
    /**
     * <code>int32 senceId = 6;</code>
     */
    public int getSenceId() {
      return senceId_;
    }

    public static final int EXP_FIELD_NUMBER = 7;
    private int exp_;
    /**
     * <code>int32 exp = 7;</code>
     */
    public int getExp() {
      return exp_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeUInt64(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (userId_ != 0) {
        output.writeInt32(3, userId_);
      }
      if (state_ != 0) {
        output.writeInt32(4, state_);
      }
      if (typeId_ != 0) {
        output.writeInt32(5, typeId_);
      }
      if (senceId_ != 0) {
        output.writeInt32(6, senceId_);
      }
      if (exp_ != 0) {
        output.writeInt32(7, exp_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, userId_);
      }
      if (state_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, state_);
      }
      if (typeId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, typeId_);
      }
      if (senceId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, senceId_);
      }
      if (exp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, exp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UserEntity)) {
        return super.equals(obj);
      }
      UserEntity other = (UserEntity) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (getState()
          != other.getState()) return false;
      if (getTypeId()
          != other.getTypeId()) return false;
      if (getSenceId()
          != other.getSenceId()) return false;
      if (getExp()
          != other.getExp()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + getState();
      hash = (37 * hash) + TYPEID_FIELD_NUMBER;
      hash = (53 * hash) + getTypeId();
      hash = (37 * hash) + SENCEID_FIELD_NUMBER;
      hash = (53 * hash) + getSenceId();
      hash = (37 * hash) + EXP_FIELD_NUMBER;
      hash = (53 * hash) + getExp();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UserEntity parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserEntity parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserEntity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserEntity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserEntity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserEntity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserEntity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserEntity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserEntity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static UserEntity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserEntity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserEntity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UserEntity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *用户角色实体
     * </pre>
     *
     * Protobuf type {@code UserEntity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserEntity)
        UserEntityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UserEntityProto.internal_static_UserEntity_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UserEntityProto.internal_static_UserEntity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UserEntity.class, Builder.class);
      }

      // Construct using org.sq.gameDemo.common.proto.UserEntityProto.UserEntity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        name_ = "";

        userId_ = 0;

        state_ = 0;

        typeId_ = 0;

        senceId_ = 0;

        exp_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UserEntityProto.internal_static_UserEntity_descriptor;
      }

      @Override
      public UserEntity getDefaultInstanceForType() {
        return UserEntity.getDefaultInstance();
      }

      @Override
      public UserEntity build() {
        UserEntity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public UserEntity buildPartial() {
        UserEntity result = new UserEntity(this);
        result.id_ = id_;
        result.name_ = name_;
        result.userId_ = userId_;
        result.state_ = state_;
        result.typeId_ = typeId_;
        result.senceId_ = senceId_;
        result.exp_ = exp_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UserEntity) {
          return mergeFrom((UserEntity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UserEntity other) {
        if (other == UserEntity.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (other.getState() != 0) {
          setState(other.getState());
        }
        if (other.getTypeId() != 0) {
          setTypeId(other.getTypeId());
        }
        if (other.getSenceId() != 0) {
          setSenceId(other.getSenceId());
        }
        if (other.getExp() != 0) {
          setExp(other.getExp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        UserEntity parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UserEntity) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>uint64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>uint64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int userId_ ;
      /**
       * <code>int32 userId = 3;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>int32 userId = 3;</code>
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 userId = 3;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }

      private int state_ ;
      /**
       * <code>int32 state = 4;</code>
       */
      public int getState() {
        return state_;
      }
      /**
       * <code>int32 state = 4;</code>
       */
      public Builder setState(int value) {
        
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 state = 4;</code>
       */
      public Builder clearState() {
        
        state_ = 0;
        onChanged();
        return this;
      }

      private int typeId_ ;
      /**
       * <code>int32 typeId = 5;</code>
       */
      public int getTypeId() {
        return typeId_;
      }
      /**
       * <code>int32 typeId = 5;</code>
       */
      public Builder setTypeId(int value) {
        
        typeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 typeId = 5;</code>
       */
      public Builder clearTypeId() {
        
        typeId_ = 0;
        onChanged();
        return this;
      }

      private int senceId_ ;
      /**
       * <code>int32 senceId = 6;</code>
       */
      public int getSenceId() {
        return senceId_;
      }
      /**
       * <code>int32 senceId = 6;</code>
       */
      public Builder setSenceId(int value) {
        
        senceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 senceId = 6;</code>
       */
      public Builder clearSenceId() {
        
        senceId_ = 0;
        onChanged();
        return this;
      }

      private int exp_ ;
      /**
       * <code>int32 exp = 7;</code>
       */
      public int getExp() {
        return exp_;
      }
      /**
       * <code>int32 exp = 7;</code>
       */
      public Builder setExp(int value) {
        
        exp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 exp = 7;</code>
       */
      public Builder clearExp() {
        
        exp_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UserEntity)
    }

    // @@protoc_insertion_point(class_scope:UserEntity)
    private static final UserEntity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserEntity();
    }

    public static UserEntity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserEntity>
        PARSER = new com.google.protobuf.AbstractParser<UserEntity>() {
      @Override
      public UserEntity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserEntity(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserEntity> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<UserEntity> getParserForType() {
      return PARSER;
    }

    @Override
    public UserEntity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserEntityRequestInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserEntityRequestInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>uint64 msg_id = 1;</code>
     */
    long getMsgId();

    /**
     * <pre>
     *时间戳(单位:毫秒)
     * </pre>
     *
     * <code>uint64 time = 2;</code>
     */
    long getTime();

    /**
     * <code>int32 typeId = 3;</code>
     */
    int getTypeId();

    /**
     * <code>int32 senceId = 4;</code>
     */
    int getSenceId();
  }
  /**
   * <pre>
   *请求
   * </pre>
   *
   * Protobuf type {@code UserEntityRequestInfo}
   */
  public  static final class UserEntityRequestInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UserEntityRequestInfo)
      UserEntityRequestInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserEntityRequestInfo.newBuilder() to construct.
    private UserEntityRequestInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserEntityRequestInfo() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserEntityRequestInfo();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserEntityRequestInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              msgId_ = input.readUInt64();
              break;
            }
            case 16: {

              time_ = input.readUInt64();
              break;
            }
            case 24: {

              typeId_ = input.readInt32();
              break;
            }
            case 32: {

              senceId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserEntityProto.internal_static_UserEntityRequestInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserEntityProto.internal_static_UserEntityRequestInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UserEntityRequestInfo.class, Builder.class);
    }

    public static final int MSG_ID_FIELD_NUMBER = 1;
    private long msgId_;
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>uint64 msg_id = 1;</code>
     */
    public long getMsgId() {
      return msgId_;
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private long time_;
    /**
     * <pre>
     *时间戳(单位:毫秒)
     * </pre>
     *
     * <code>uint64 time = 2;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int TYPEID_FIELD_NUMBER = 3;
    private int typeId_;
    /**
     * <code>int32 typeId = 3;</code>
     */
    public int getTypeId() {
      return typeId_;
    }

    public static final int SENCEID_FIELD_NUMBER = 4;
    private int senceId_;
    /**
     * <code>int32 senceId = 4;</code>
     */
    public int getSenceId() {
      return senceId_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgId_ != 0L) {
        output.writeUInt64(1, msgId_);
      }
      if (time_ != 0L) {
        output.writeUInt64(2, time_);
      }
      if (typeId_ != 0) {
        output.writeInt32(3, typeId_);
      }
      if (senceId_ != 0) {
        output.writeInt32(4, senceId_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, msgId_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, time_);
      }
      if (typeId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, typeId_);
      }
      if (senceId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, senceId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UserEntityRequestInfo)) {
        return super.equals(obj);
      }
      UserEntityRequestInfo other = (UserEntityRequestInfo) obj;

      if (getMsgId()
          != other.getMsgId()) return false;
      if (getTime()
          != other.getTime()) return false;
      if (getTypeId()
          != other.getTypeId()) return false;
      if (getSenceId()
          != other.getSenceId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSG_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgId());
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (37 * hash) + TYPEID_FIELD_NUMBER;
      hash = (53 * hash) + getTypeId();
      hash = (37 * hash) + SENCEID_FIELD_NUMBER;
      hash = (53 * hash) + getSenceId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UserEntityRequestInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserEntityRequestInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserEntityRequestInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserEntityRequestInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserEntityRequestInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserEntityRequestInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserEntityRequestInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserEntityRequestInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserEntityRequestInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static UserEntityRequestInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserEntityRequestInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserEntityRequestInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UserEntityRequestInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *请求
     * </pre>
     *
     * Protobuf type {@code UserEntityRequestInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserEntityRequestInfo)
        UserEntityRequestInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UserEntityProto.internal_static_UserEntityRequestInfo_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UserEntityProto.internal_static_UserEntityRequestInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UserEntityRequestInfo.class, Builder.class);
      }

      // Construct using org.sq.gameDemo.common.proto.UserEntityProto.UserEntityRequestInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        msgId_ = 0L;

        time_ = 0L;

        typeId_ = 0;

        senceId_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UserEntityProto.internal_static_UserEntityRequestInfo_descriptor;
      }

      @Override
      public UserEntityRequestInfo getDefaultInstanceForType() {
        return UserEntityRequestInfo.getDefaultInstance();
      }

      @Override
      public UserEntityRequestInfo build() {
        UserEntityRequestInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public UserEntityRequestInfo buildPartial() {
        UserEntityRequestInfo result = new UserEntityRequestInfo(this);
        result.msgId_ = msgId_;
        result.time_ = time_;
        result.typeId_ = typeId_;
        result.senceId_ = senceId_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UserEntityRequestInfo) {
          return mergeFrom((UserEntityRequestInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UserEntityRequestInfo other) {
        if (other == UserEntityRequestInfo.getDefaultInstance()) return this;
        if (other.getMsgId() != 0L) {
          setMsgId(other.getMsgId());
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (other.getTypeId() != 0) {
          setTypeId(other.getTypeId());
        }
        if (other.getSenceId() != 0) {
          setSenceId(other.getSenceId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        UserEntityRequestInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UserEntityRequestInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long msgId_ ;
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>uint64 msg_id = 1;</code>
       */
      public long getMsgId() {
        return msgId_;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>uint64 msg_id = 1;</code>
       */
      public Builder setMsgId(long value) {
        
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>uint64 msg_id = 1;</code>
       */
      public Builder clearMsgId() {
        
        msgId_ = 0L;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <pre>
       *时间戳(单位:毫秒)
       * </pre>
       *
       * <code>uint64 time = 2;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <pre>
       *时间戳(单位:毫秒)
       * </pre>
       *
       * <code>uint64 time = 2;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间戳(单位:毫秒)
       * </pre>
       *
       * <code>uint64 time = 2;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private int typeId_ ;
      /**
       * <code>int32 typeId = 3;</code>
       */
      public int getTypeId() {
        return typeId_;
      }
      /**
       * <code>int32 typeId = 3;</code>
       */
      public Builder setTypeId(int value) {
        
        typeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 typeId = 3;</code>
       */
      public Builder clearTypeId() {
        
        typeId_ = 0;
        onChanged();
        return this;
      }

      private int senceId_ ;
      /**
       * <code>int32 senceId = 4;</code>
       */
      public int getSenceId() {
        return senceId_;
      }
      /**
       * <code>int32 senceId = 4;</code>
       */
      public Builder setSenceId(int value) {
        
        senceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 senceId = 4;</code>
       */
      public Builder clearSenceId() {
        
        senceId_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UserEntityRequestInfo)
    }

    // @@protoc_insertion_point(class_scope:UserEntityRequestInfo)
    private static final UserEntityRequestInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserEntityRequestInfo();
    }

    public static UserEntityRequestInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserEntityRequestInfo>
        PARSER = new com.google.protobuf.AbstractParser<UserEntityRequestInfo>() {
      @Override
      public UserEntityRequestInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserEntityRequestInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserEntityRequestInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<UserEntityRequestInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public UserEntityRequestInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserEntityResponseInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserEntityResponseInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>uint64 msg_id = 1;</code>
     */
    long getMsgId();

    /**
     * <code>int32 result = 2;</code>
     */
    int getResult();

    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>uint64 time = 3;</code>
     */
    long getTime();

    /**
     * <code>string content = 4;</code>
     */
    String getContent();
    /**
     * <code>string content = 4;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>repeated .EntityType type = 5;</code>
     */
    java.util.List<EntityTypeProto.EntityType>
        getTypeList();
    /**
     * <code>repeated .EntityType type = 5;</code>
     */
    EntityTypeProto.EntityType getType(int index);
    /**
     * <code>repeated .EntityType type = 5;</code>
     */
    int getTypeCount();
    /**
     * <code>repeated .EntityType type = 5;</code>
     */
    java.util.List<? extends EntityTypeProto.EntityTypeOrBuilder>
        getTypeOrBuilderList();
    /**
     * <code>repeated .EntityType type = 5;</code>
     */
    EntityTypeProto.EntityTypeOrBuilder getTypeOrBuilder(
            int index);

    /**
     * <code>repeated .UserEntity userEntity = 6;</code>
     */
    java.util.List<UserEntity>
        getUserEntityList();
    /**
     * <code>repeated .UserEntity userEntity = 6;</code>
     */
    UserEntity getUserEntity(int index);
    /**
     * <code>repeated .UserEntity userEntity = 6;</code>
     */
    int getUserEntityCount();
    /**
     * <code>repeated .UserEntity userEntity = 6;</code>
     */
    java.util.List<? extends UserEntityOrBuilder>
        getUserEntityOrBuilderList();
    /**
     * <code>repeated .UserEntity userEntity = 6;</code>
     */
    UserEntityOrBuilder getUserEntityOrBuilder(
            int index);
  }
  /**
   * <pre>
   *响应
   * </pre>
   *
   * Protobuf type {@code UserEntityResponseInfo}
   */
  public  static final class UserEntityResponseInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UserEntityResponseInfo)
      UserEntityResponseInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserEntityResponseInfo.newBuilder() to construct.
    private UserEntityResponseInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserEntityResponseInfo() {
      content_ = "";
      type_ = java.util.Collections.emptyList();
      userEntity_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserEntityResponseInfo();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserEntityResponseInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              msgId_ = input.readUInt64();
              break;
            }
            case 16: {

              result_ = input.readInt32();
              break;
            }
            case 24: {

              time_ = input.readUInt64();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                type_ = new java.util.ArrayList<EntityTypeProto.EntityType>();
                mutable_bitField0_ |= 0x00000001;
              }
              type_.add(
                  input.readMessage(EntityTypeProto.EntityType.parser(), extensionRegistry));
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                userEntity_ = new java.util.ArrayList<UserEntity>();
                mutable_bitField0_ |= 0x00000002;
              }
              userEntity_.add(
                  input.readMessage(UserEntity.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          type_ = java.util.Collections.unmodifiableList(type_);
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          userEntity_ = java.util.Collections.unmodifiableList(userEntity_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserEntityProto.internal_static_UserEntityResponseInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserEntityProto.internal_static_UserEntityResponseInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UserEntityResponseInfo.class, Builder.class);
    }

    public static final int MSG_ID_FIELD_NUMBER = 1;
    private long msgId_;
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>uint64 msg_id = 1;</code>
     */
    public long getMsgId() {
      return msgId_;
    }

    public static final int RESULT_FIELD_NUMBER = 2;
    private int result_;
    /**
     * <code>int32 result = 2;</code>
     */
    public int getResult() {
      return result_;
    }

    public static final int TIME_FIELD_NUMBER = 3;
    private long time_;
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>uint64 time = 3;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    private volatile Object content_;
    /**
     * <code>string content = 4;</code>
     */
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 4;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 5;
    private java.util.List<EntityTypeProto.EntityType> type_;
    /**
     * <code>repeated .EntityType type = 5;</code>
     */
    public java.util.List<EntityTypeProto.EntityType> getTypeList() {
      return type_;
    }
    /**
     * <code>repeated .EntityType type = 5;</code>
     */
    public java.util.List<? extends EntityTypeProto.EntityTypeOrBuilder>
        getTypeOrBuilderList() {
      return type_;
    }
    /**
     * <code>repeated .EntityType type = 5;</code>
     */
    public int getTypeCount() {
      return type_.size();
    }
    /**
     * <code>repeated .EntityType type = 5;</code>
     */
    public EntityTypeProto.EntityType getType(int index) {
      return type_.get(index);
    }
    /**
     * <code>repeated .EntityType type = 5;</code>
     */
    public EntityTypeProto.EntityTypeOrBuilder getTypeOrBuilder(
        int index) {
      return type_.get(index);
    }

    public static final int USERENTITY_FIELD_NUMBER = 6;
    private java.util.List<UserEntity> userEntity_;
    /**
     * <code>repeated .UserEntity userEntity = 6;</code>
     */
    public java.util.List<UserEntity> getUserEntityList() {
      return userEntity_;
    }
    /**
     * <code>repeated .UserEntity userEntity = 6;</code>
     */
    public java.util.List<? extends UserEntityOrBuilder>
        getUserEntityOrBuilderList() {
      return userEntity_;
    }
    /**
     * <code>repeated .UserEntity userEntity = 6;</code>
     */
    public int getUserEntityCount() {
      return userEntity_.size();
    }
    /**
     * <code>repeated .UserEntity userEntity = 6;</code>
     */
    public UserEntity getUserEntity(int index) {
      return userEntity_.get(index);
    }
    /**
     * <code>repeated .UserEntity userEntity = 6;</code>
     */
    public UserEntityOrBuilder getUserEntityOrBuilder(
        int index) {
      return userEntity_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgId_ != 0L) {
        output.writeUInt64(1, msgId_);
      }
      if (result_ != 0) {
        output.writeInt32(2, result_);
      }
      if (time_ != 0L) {
        output.writeUInt64(3, time_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, content_);
      }
      for (int i = 0; i < type_.size(); i++) {
        output.writeMessage(5, type_.get(i));
      }
      for (int i = 0; i < userEntity_.size(); i++) {
        output.writeMessage(6, userEntity_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, msgId_);
      }
      if (result_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, result_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, time_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, content_);
      }
      for (int i = 0; i < type_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, type_.get(i));
      }
      for (int i = 0; i < userEntity_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, userEntity_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UserEntityResponseInfo)) {
        return super.equals(obj);
      }
      UserEntityResponseInfo other = (UserEntityResponseInfo) obj;

      if (getMsgId()
          != other.getMsgId()) return false;
      if (getResult()
          != other.getResult()) return false;
      if (getTime()
          != other.getTime()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!getTypeList()
          .equals(other.getTypeList())) return false;
      if (!getUserEntityList()
          .equals(other.getUserEntityList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSG_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgId());
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      if (getTypeCount() > 0) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getTypeList().hashCode();
      }
      if (getUserEntityCount() > 0) {
        hash = (37 * hash) + USERENTITY_FIELD_NUMBER;
        hash = (53 * hash) + getUserEntityList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UserEntityResponseInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserEntityResponseInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserEntityResponseInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserEntityResponseInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserEntityResponseInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserEntityResponseInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserEntityResponseInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserEntityResponseInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserEntityResponseInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static UserEntityResponseInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserEntityResponseInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserEntityResponseInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UserEntityResponseInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *响应
     * </pre>
     *
     * Protobuf type {@code UserEntityResponseInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserEntityResponseInfo)
        UserEntityResponseInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UserEntityProto.internal_static_UserEntityResponseInfo_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UserEntityProto.internal_static_UserEntityResponseInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UserEntityResponseInfo.class, Builder.class);
      }

      // Construct using org.sq.gameDemo.common.proto.UserEntityProto.UserEntityResponseInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTypeFieldBuilder();
          getUserEntityFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        msgId_ = 0L;

        result_ = 0;

        time_ = 0L;

        content_ = "";

        if (typeBuilder_ == null) {
          type_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          typeBuilder_.clear();
        }
        if (userEntityBuilder_ == null) {
          userEntity_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          userEntityBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UserEntityProto.internal_static_UserEntityResponseInfo_descriptor;
      }

      @Override
      public UserEntityResponseInfo getDefaultInstanceForType() {
        return UserEntityResponseInfo.getDefaultInstance();
      }

      @Override
      public UserEntityResponseInfo build() {
        UserEntityResponseInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public UserEntityResponseInfo buildPartial() {
        UserEntityResponseInfo result = new UserEntityResponseInfo(this);
        int from_bitField0_ = bitField0_;
        result.msgId_ = msgId_;
        result.result_ = result_;
        result.time_ = time_;
        result.content_ = content_;
        if (typeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            type_ = java.util.Collections.unmodifiableList(type_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.type_ = type_;
        } else {
          result.type_ = typeBuilder_.build();
        }
        if (userEntityBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            userEntity_ = java.util.Collections.unmodifiableList(userEntity_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.userEntity_ = userEntity_;
        } else {
          result.userEntity_ = userEntityBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UserEntityResponseInfo) {
          return mergeFrom((UserEntityResponseInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UserEntityResponseInfo other) {
        if (other == UserEntityResponseInfo.getDefaultInstance()) return this;
        if (other.getMsgId() != 0L) {
          setMsgId(other.getMsgId());
        }
        if (other.getResult() != 0) {
          setResult(other.getResult());
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (typeBuilder_ == null) {
          if (!other.type_.isEmpty()) {
            if (type_.isEmpty()) {
              type_ = other.type_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTypeIsMutable();
              type_.addAll(other.type_);
            }
            onChanged();
          }
        } else {
          if (!other.type_.isEmpty()) {
            if (typeBuilder_.isEmpty()) {
              typeBuilder_.dispose();
              typeBuilder_ = null;
              type_ = other.type_;
              bitField0_ = (bitField0_ & ~0x00000001);
              typeBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTypeFieldBuilder() : null;
            } else {
              typeBuilder_.addAllMessages(other.type_);
            }
          }
        }
        if (userEntityBuilder_ == null) {
          if (!other.userEntity_.isEmpty()) {
            if (userEntity_.isEmpty()) {
              userEntity_ = other.userEntity_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureUserEntityIsMutable();
              userEntity_.addAll(other.userEntity_);
            }
            onChanged();
          }
        } else {
          if (!other.userEntity_.isEmpty()) {
            if (userEntityBuilder_.isEmpty()) {
              userEntityBuilder_.dispose();
              userEntityBuilder_ = null;
              userEntity_ = other.userEntity_;
              bitField0_ = (bitField0_ & ~0x00000002);
              userEntityBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getUserEntityFieldBuilder() : null;
            } else {
              userEntityBuilder_.addAllMessages(other.userEntity_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        UserEntityResponseInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UserEntityResponseInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long msgId_ ;
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>uint64 msg_id = 1;</code>
       */
      public long getMsgId() {
        return msgId_;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>uint64 msg_id = 1;</code>
       */
      public Builder setMsgId(long value) {
        
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>uint64 msg_id = 1;</code>
       */
      public Builder clearMsgId() {
        
        msgId_ = 0L;
        onChanged();
        return this;
      }

      private int result_ ;
      /**
       * <code>int32 result = 2;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>int32 result = 2;</code>
       */
      public Builder setResult(int value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 result = 2;</code>
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>uint64 time = 3;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>uint64 time = 3;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>uint64 time = 3;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <code>string content = 4;</code>
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string content = 4;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 4;</code>
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 4;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 4;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private java.util.List<EntityTypeProto.EntityType> type_ =
        java.util.Collections.emptyList();
      private void ensureTypeIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          type_ = new java.util.ArrayList<EntityTypeProto.EntityType>(type_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          EntityTypeProto.EntityType, EntityTypeProto.EntityType.Builder, EntityTypeProto.EntityTypeOrBuilder> typeBuilder_;

      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public java.util.List<EntityTypeProto.EntityType> getTypeList() {
        if (typeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(type_);
        } else {
          return typeBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public int getTypeCount() {
        if (typeBuilder_ == null) {
          return type_.size();
        } else {
          return typeBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public EntityTypeProto.EntityType getType(int index) {
        if (typeBuilder_ == null) {
          return type_.get(index);
        } else {
          return typeBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public Builder setType(
          int index, EntityTypeProto.EntityType value) {
        if (typeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTypeIsMutable();
          type_.set(index, value);
          onChanged();
        } else {
          typeBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public Builder setType(
          int index, EntityTypeProto.EntityType.Builder builderForValue) {
        if (typeBuilder_ == null) {
          ensureTypeIsMutable();
          type_.set(index, builderForValue.build());
          onChanged();
        } else {
          typeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public Builder addType(EntityTypeProto.EntityType value) {
        if (typeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTypeIsMutable();
          type_.add(value);
          onChanged();
        } else {
          typeBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public Builder addType(
          int index, EntityTypeProto.EntityType value) {
        if (typeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTypeIsMutable();
          type_.add(index, value);
          onChanged();
        } else {
          typeBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public Builder addType(
          EntityTypeProto.EntityType.Builder builderForValue) {
        if (typeBuilder_ == null) {
          ensureTypeIsMutable();
          type_.add(builderForValue.build());
          onChanged();
        } else {
          typeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public Builder addType(
          int index, EntityTypeProto.EntityType.Builder builderForValue) {
        if (typeBuilder_ == null) {
          ensureTypeIsMutable();
          type_.add(index, builderForValue.build());
          onChanged();
        } else {
          typeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public Builder addAllType(
          Iterable<? extends EntityTypeProto.EntityType> values) {
        if (typeBuilder_ == null) {
          ensureTypeIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, type_);
          onChanged();
        } else {
          typeBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public Builder clearType() {
        if (typeBuilder_ == null) {
          type_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          typeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public Builder removeType(int index) {
        if (typeBuilder_ == null) {
          ensureTypeIsMutable();
          type_.remove(index);
          onChanged();
        } else {
          typeBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public EntityTypeProto.EntityType.Builder getTypeBuilder(
          int index) {
        return getTypeFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public EntityTypeProto.EntityTypeOrBuilder getTypeOrBuilder(
          int index) {
        if (typeBuilder_ == null) {
          return type_.get(index);  } else {
          return typeBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public java.util.List<? extends EntityTypeProto.EntityTypeOrBuilder>
           getTypeOrBuilderList() {
        if (typeBuilder_ != null) {
          return typeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(type_);
        }
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public EntityTypeProto.EntityType.Builder addTypeBuilder() {
        return getTypeFieldBuilder().addBuilder(
            EntityTypeProto.EntityType.getDefaultInstance());
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public EntityTypeProto.EntityType.Builder addTypeBuilder(
          int index) {
        return getTypeFieldBuilder().addBuilder(
            index, EntityTypeProto.EntityType.getDefaultInstance());
      }
      /**
       * <code>repeated .EntityType type = 5;</code>
       */
      public java.util.List<EntityTypeProto.EntityType.Builder>
           getTypeBuilderList() {
        return getTypeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          EntityTypeProto.EntityType, EntityTypeProto.EntityType.Builder, EntityTypeProto.EntityTypeOrBuilder>
          getTypeFieldBuilder() {
        if (typeBuilder_ == null) {
          typeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              EntityTypeProto.EntityType, EntityTypeProto.EntityType.Builder, EntityTypeProto.EntityTypeOrBuilder>(
                  type_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          type_ = null;
        }
        return typeBuilder_;
      }

      private java.util.List<UserEntity> userEntity_ =
        java.util.Collections.emptyList();
      private void ensureUserEntityIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          userEntity_ = new java.util.ArrayList<UserEntity>(userEntity_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          UserEntity, UserEntity.Builder, UserEntityOrBuilder> userEntityBuilder_;

      /**
       * <code>repeated .UserEntity userEntity = 6;</code>
       */
      public java.util.List<UserEntity> getUserEntityList() {
        if (userEntityBuilder_ == null) {
          return java.util.Collections.unmodifiableList(userEntity_);
        } else {
          return userEntityBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .UserEntity userEntity = 6;</code>
       */
      public int getUserEntityCount() {
        if (userEntityBuilder_ == null) {
          return userEntity_.size();
        } else {
          return userEntityBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .UserEntity userEntity = 6;</code>
       */
      public UserEntity getUserEntity(int index) {
        if (userEntityBuilder_ == null) {
          return userEntity_.get(index);
        } else {
          return userEntityBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .UserEntity userEntity = 6;</code>
       */
      public Builder setUserEntity(
          int index, UserEntity value) {
        if (userEntityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserEntityIsMutable();
          userEntity_.set(index, value);
          onChanged();
        } else {
          userEntityBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .UserEntity userEntity = 6;</code>
       */
      public Builder setUserEntity(
          int index, UserEntity.Builder builderForValue) {
        if (userEntityBuilder_ == null) {
          ensureUserEntityIsMutable();
          userEntity_.set(index, builderForValue.build());
          onChanged();
        } else {
          userEntityBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .UserEntity userEntity = 6;</code>
       */
      public Builder addUserEntity(UserEntity value) {
        if (userEntityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserEntityIsMutable();
          userEntity_.add(value);
          onChanged();
        } else {
          userEntityBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .UserEntity userEntity = 6;</code>
       */
      public Builder addUserEntity(
          int index, UserEntity value) {
        if (userEntityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserEntityIsMutable();
          userEntity_.add(index, value);
          onChanged();
        } else {
          userEntityBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .UserEntity userEntity = 6;</code>
       */
      public Builder addUserEntity(
          UserEntity.Builder builderForValue) {
        if (userEntityBuilder_ == null) {
          ensureUserEntityIsMutable();
          userEntity_.add(builderForValue.build());
          onChanged();
        } else {
          userEntityBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .UserEntity userEntity = 6;</code>
       */
      public Builder addUserEntity(
          int index, UserEntity.Builder builderForValue) {
        if (userEntityBuilder_ == null) {
          ensureUserEntityIsMutable();
          userEntity_.add(index, builderForValue.build());
          onChanged();
        } else {
          userEntityBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .UserEntity userEntity = 6;</code>
       */
      public Builder addAllUserEntity(
          Iterable<? extends UserEntity> values) {
        if (userEntityBuilder_ == null) {
          ensureUserEntityIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, userEntity_);
          onChanged();
        } else {
          userEntityBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .UserEntity userEntity = 6;</code>
       */
      public Builder clearUserEntity() {
        if (userEntityBuilder_ == null) {
          userEntity_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          userEntityBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .UserEntity userEntity = 6;</code>
       */
      public Builder removeUserEntity(int index) {
        if (userEntityBuilder_ == null) {
          ensureUserEntityIsMutable();
          userEntity_.remove(index);
          onChanged();
        } else {
          userEntityBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .UserEntity userEntity = 6;</code>
       */
      public UserEntity.Builder getUserEntityBuilder(
          int index) {
        return getUserEntityFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .UserEntity userEntity = 6;</code>
       */
      public UserEntityOrBuilder getUserEntityOrBuilder(
          int index) {
        if (userEntityBuilder_ == null) {
          return userEntity_.get(index);  } else {
          return userEntityBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .UserEntity userEntity = 6;</code>
       */
      public java.util.List<? extends UserEntityOrBuilder>
           getUserEntityOrBuilderList() {
        if (userEntityBuilder_ != null) {
          return userEntityBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(userEntity_);
        }
      }
      /**
       * <code>repeated .UserEntity userEntity = 6;</code>
       */
      public UserEntity.Builder addUserEntityBuilder() {
        return getUserEntityFieldBuilder().addBuilder(
            UserEntity.getDefaultInstance());
      }
      /**
       * <code>repeated .UserEntity userEntity = 6;</code>
       */
      public UserEntity.Builder addUserEntityBuilder(
          int index) {
        return getUserEntityFieldBuilder().addBuilder(
            index, UserEntity.getDefaultInstance());
      }
      /**
       * <code>repeated .UserEntity userEntity = 6;</code>
       */
      public java.util.List<UserEntity.Builder>
           getUserEntityBuilderList() {
        return getUserEntityFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          UserEntity, UserEntity.Builder, UserEntityOrBuilder>
          getUserEntityFieldBuilder() {
        if (userEntityBuilder_ == null) {
          userEntityBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              UserEntity, UserEntity.Builder, UserEntityOrBuilder>(
                  userEntity_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          userEntity_ = null;
        }
        return userEntityBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UserEntityResponseInfo)
    }

    // @@protoc_insertion_point(class_scope:UserEntityResponseInfo)
    private static final UserEntityResponseInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserEntityResponseInfo();
    }

    public static UserEntityResponseInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserEntityResponseInfo>
        PARSER = new com.google.protobuf.AbstractParser<UserEntityResponseInfo>() {
      @Override
      public UserEntityResponseInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserEntityResponseInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserEntityResponseInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<UserEntityResponseInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public UserEntityResponseInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserEntity_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserEntity_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserEntityRequestInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserEntityRequestInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserEntityResponseInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserEntityResponseInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020UserEntity.proto\032\020EntityType.proto\"s\n\n" +
      "UserEntity\022\n\n\002id\030\001 \001(\004\022\014\n\004name\030\002 \001(\t\022\016\n\006" +
      "userId\030\003 \001(\005\022\r\n\005state\030\004 \001(\005\022\016\n\006typeId\030\005 " +
      "\001(\005\022\017\n\007senceId\030\006 \001(\005\022\013\n\003exp\030\007 \001(\005\"V\n\025Use" +
      "rEntityRequestInfo\022\016\n\006msg_id\030\001 \001(\004\022\014\n\004ti" +
      "me\030\002 \001(\004\022\016\n\006typeId\030\003 \001(\005\022\017\n\007senceId\030\004 \001(" +
      "\005\"\223\001\n\026UserEntityResponseInfo\022\016\n\006msg_id\030\001" +
      " \001(\004\022\016\n\006result\030\002 \001(\005\022\014\n\004time\030\003 \001(\004\022\017\n\007co" +
      "ntent\030\004 \001(\t\022\031\n\004type\030\005 \003(\0132\013.EntityType\022\037" +
      "\n\nuserEntity\030\006 \003(\0132\013.UserEntityB/\n\034org.s" +
      "q.gameDemo.common.protoB\017UserEntityProto" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          EntityTypeProto.getDescriptor(),
        });
    internal_static_UserEntity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserEntity_descriptor,
        new String[] { "Id", "Name", "UserId", "State", "TypeId", "SenceId", "Exp", });
    internal_static_UserEntityRequestInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UserEntityRequestInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserEntityRequestInfo_descriptor,
        new String[] { "MsgId", "Time", "TypeId", "SenceId", });
    internal_static_UserEntityResponseInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UserEntityResponseInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserEntityResponseInfo_descriptor,
        new String[] { "MsgId", "Result", "Time", "Content", "Type", "UserEntity", });
    EntityTypeProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
